/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 *
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/minecraft110.xml
 */
package sul.protocol.minecraft110.serverbound;

import sul.utils.*;

public class EnchantItem extends Packet {

	public final static int ID = (int)6;

	public final static boolean CLIENTBOUND = false;
	public final static boolean SERVERBOUND = true;

	public byte window;
	public byte enchantment;

	public EnchantItem() {}

	public EnchantItem(byte window, byte enchantment) {
		this.window = window;
		this.enchantment = enchantment;
	}

	@Override
	public int length() {
		return Var.Uint.length() + 2;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeVaruint(ID);
		this.writeBigEndianByte(window);
		this.writeBigEndianByte(enchantment);
		return this._buffer;
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		varuint.decode(_buffer, _index);
		window=readBigEndianByte();
		enchantment=readBigEndianByte();
	}

	public static EnchantItem fromBuffer(byte[] buffer) {
		EnchantItem ret = new EnchantItem();
		ret.decode(buffer);
		return ret;
	}

}
