/*
 * This file has been automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 *
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generator: https://github.com/sel-project/sel-utils/blob/master/xml/protocol/minecraft316.xml
 */
package sul.protocol.minecraft316.clientbound;

import java.util.UUID;

import sul.protocol.minecraft316.types.*;
import sul.utils.*;

class EntityStatus extends Packet {

	public final static int ID = (int)27;

	public final static boolean CLIENTBOUND = true;
	public final static boolean SERVERBOUND = false;

	// status
	public final static byte SPAWN_TIPPED_ARROW_PARTICLE_EFFECTS = (byte)0;
	public final static byte PLAY_JUMPING_ANIMATION_AND_PARTICLES = (byte)1;
	public final static byte RESET_SPAWNER_DELAY = (byte)1;
	public final static byte PLAY_HURT_ANIMATION_AND_SOUND = (byte)2;
	public final static byte PLAY_DEAD_ANIMATION_AND_SOUND = (byte)3;
	public final static byte PLAY_ATTACK_ANIMATION_AND_SOUND = (byte)4;
	public final static byte SPAWN_SMOKE_PARTICLES = (byte)6;
	public final static byte SPAWN_HEART_PARTICLES = (byte)7;
	public final static byte PLAY_SHAKING_WATER_ANIMATION = (byte)8;
	public final static byte FINISHED_CONSUMING = (byte)9;
	public final static byte PLAY_EATING_GRASS_ANIMATION = (byte)10;
	public final static byte IGNITE_MINECART_TNT = (byte)10;
	public final static byte HOLD_POPPY = (byte)11;
	public final static byte SPAWN_VILLAGER_MATING_HEART_PARTICLES = (byte)12;
	public final static byte SPAWN_VILLAGER_ANGRY_PARTICLES = (byte)13;
	public final static byte SPAWN_VILLAGER_HAPPY_PARTICLES = (byte)14;
	public final static byte SPAWN_WITCH_MAGIC_PARTICLES = (byte)15;
	public final static byte PLAY_ZOMBIE_CURE_FINISHED_SOUND = (byte)16;
	public final static byte SPAWN_FIREWORK_EXPLOSION_EFFECT = (byte)17;
	public final static byte SPAWN_LOVE_PARTICLES = (byte)18;
	public final static byte RESET_SQUID_ROTATION = (byte)19;
	public final static byte SPAWN_EXPLOSION_PARTICLES = (byte)20;
	public final static byte PLAY_GUARDIAN_SOUND_EFFECT = (byte)21;
	public final static byte ENABLE_REDUCED_DEBUG_SCREEN = (byte)22;
	public final static byte DISABLE_REDUCED_DEBUG_SCREEN = (byte)23;
	public final static byte SET_OP_PERMISSION_LEVEL_0 = (byte)24;
	public final static byte SET_OP_PERMISSION_LEVEL_1 = (byte)25;
	public final static byte SET_OP_PERMISSION_LEVEL_2 = (byte)26;
	public final static byte SET_OP_PERMISSION_LEVEL_3 = (byte)27;
	public final static byte SET_OP_PERMISSION_LEVEL_4 = (byte)28;
	public final static byte PLAY_SHIELD_BLOCK_SOUND = (byte)29;
	public final static byte PLAY_SHIELD_BREAK_SOUND = (byte)30;
	public final static byte HOOK_KNOCKBACK = (byte)31;
	public final static byte PLAY_HIT_SOUND = (byte)32;
	public final static byte PLAY_THORNS_HURT_ANIMATION_AND_SOUND = (byte)33;
	public final static byte REMOVE_POPPY = (byte)34;
	public final static byte PLAY_TOTEM_UNDYING_ANIMATION = (byte)35;

	public int entityId;
	public byte status;

	@Override
	public int length() {
		return 5;
	}

	@Override
	public byte[] encode() {
	}

	@Override
	public void decode(byte[] buffer) {
	}

}
