/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/minecraft210.xml
 */
package sul.protocol.minecraft210.clientbound;

import sul.utils.*;

public class PlayerPositionAndLook extends Packet {

	public static final int ID = (int)46;

	public static final boolean CLIENTBOUND = true;
	public static final boolean SERVERBOUND = false;

	@Override
	public int getId() {
		return ID;
	}

	// flags
	public static final byte X = 1;
	public static final byte Y = 2;
	public static final byte Z = 4;
	public static final byte Y_ROTATION = 8;
	public static final byte X_ROTATION = 16;

	public Tuples.DoubleXYZ position = new Tuples.DoubleXYZ();
	public float yaw;
	public float pitch;
	public byte flags;
	public int teleportId;

	public PlayerPositionAndLook() {}

	public PlayerPositionAndLook(Tuples.DoubleXYZ position, float yaw, float pitch, byte flags, int teleportId) {
		this.position = position;
		this.yaw = yaw;
		this.pitch = pitch;
		this.flags = flags;
		this.teleportId = teleportId;
	}

	@Override
	public int length() {
		return Buffer.varuintLength(teleportId) + 34;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeVaruint(ID);
		this.writeBigEndianDouble(position.x); this.writeBigEndianDouble(position.y); this.writeBigEndianDouble(position.z);
		this.writeBigEndianFloat(yaw);
		this.writeBigEndianFloat(pitch);
		this.writeBigEndianByte(flags);
		this.writeVaruint(teleportId);
		return this.getBuffer();
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		this.readVaruint();
		position=new Tuples.DoubleXYZ(); position.x=readBigEndianDouble(); position.y=readBigEndianDouble(); position.z=readBigEndianDouble();
		yaw=readBigEndianFloat();
		pitch=readBigEndianFloat();
		flags=readBigEndianByte();
		teleportId=this.readVaruint();
	}

	public static PlayerPositionAndLook fromBuffer(byte[] buffer) {
		PlayerPositionAndLook ret = new PlayerPositionAndLook();
		ret.decode(buffer);
		return ret;
	}

	@Override
	public String toString() {
		return "PlayerPositionAndLook(position: " + this.position.toString() + ", yaw: " + this.yaw + ", pitch: " + this.pitch + ", flags: " + this.flags + ", teleportId: " + this.teleportId + ")";
	}

}
