/*
 * This file has been automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 *
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generator: https://github.com/sel-project/sel-utils/blob/master/xml/protocol/minecraft210.xml
 */
package sul.protocol.minecraft210.clientbound;

import java.util.UUID;

import sul.protocol.minecraft210.types.*;
import sul.utils.*;

class UpdateScore extends Packet {

	public final static int ID = (int)66;

	public final static boolean CLIENTBOUND = true;
	public final static boolean SERVERBOUND = false;

	// action
	public final static byte UPDATE = (byte)0;
	public final static byte REMOVE = (byte)1;

	public String scoreName;
	public byte action;
	public String objectiveName;
	public int value;

	@Override
	public int length() {
		return Var.Uint.length(scoreName.getBytes(StandardCharset.UTF_8).length) + scoreName.getBytes(StandardCharset.UTF_8).length + Var.Uint.length(objectiveName.getBytes(StandardCharset.UTF_8).length) + objectiveName.getBytes(StandardCharset.UTF_8).length + Var.Uint.length(value) + 1;
	}

	@Override
	public byte[] encode() {
	}

	@Override
	public void decode(byte[] buffer) {
	}

}
