/*
 * This file has been automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 *
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generator: https://github.com/sel-project/sel-utils/blob/master/xml/metadata/minecraft316.xml
 */
module sul.metadata.minecraft316;

import std.typecons : Tuple, tuple;

import sul.utils.buffer : Buffer;
import sul.utils.var;

static import sul.protocol.minecraft316.types;

alias Changed(T) = Tuple!(T, "value", bool, "changed");

class Metadata {

	private Changed!(byte) _entityFlags;

	public pure nothrow @property @safe @nogc byte entityFlags() {
		return _entityFlags.value;
	}

	public pure nothrow @property @safe @nogc byte entityFlags(byte value) {
		_entityFlags.changed = true;
		_entityFlags.value = value;
		return value;
	}

	public pure nothrow @property @safe @nogc bool onFire() {
		return (_entityFlags.value >>> 0) & 1;
	}

	public pure nothrow @property @safe @nogc bool onFire(bool value) {
		_entityFlags.changed = true;
		if(value) _entityFlags.value |= (cast(byte)true << 0);
		else _entityFlags.value &= ~(cast(byte)true << 0);
		return value;
	}

	public pure nothrow @property @safe @nogc bool sneaking() {
		return (_entityFlags.value >>> 1) & 1;
	}

	public pure nothrow @property @safe @nogc bool sneaking(bool value) {
		_entityFlags.changed = true;
		if(value) _entityFlags.value |= (cast(byte)true << 1);
		else _entityFlags.value &= ~(cast(byte)true << 1);
		return value;
	}

	public pure nothrow @property @safe @nogc bool sprinting() {
		return (_entityFlags.value >>> 3) & 1;
	}

	public pure nothrow @property @safe @nogc bool sprinting(bool value) {
		_entityFlags.changed = true;
		if(value) _entityFlags.value |= (cast(byte)true << 3);
		else _entityFlags.value &= ~(cast(byte)true << 3);
		return value;
	}

	public pure nothrow @property @safe @nogc bool invisible() {
		return (_entityFlags.value >>> 5) & 1;
	}

	public pure nothrow @property @safe @nogc bool invisible(bool value) {
		_entityFlags.changed = true;
		if(value) _entityFlags.value |= (cast(byte)true << 5);
		else _entityFlags.value &= ~(cast(byte)true << 5);
		return value;
	}

	public pure nothrow @property @safe @nogc bool glowing() {
		return (_entityFlags.value >>> 6) & 1;
	}

	public pure nothrow @property @safe @nogc bool glowing(bool value) {
		_entityFlags.changed = true;
		if(value) _entityFlags.value |= (cast(byte)true << 6);
		else _entityFlags.value &= ~(cast(byte)true << 6);
		return value;
	}

	public pure nothrow @property @safe @nogc bool gliding() {
		return (_entityFlags.value >>> 7) & 1;
	}

	public pure nothrow @property @safe @nogc bool gliding(bool value) {
		_entityFlags.changed = true;
		if(value) _entityFlags.value |= (cast(byte)true << 7);
		else _entityFlags.value &= ~(cast(byte)true << 7);
		return value;
	}

	private Changed!(uint) _air = tuple(cast(uint)300, false);

	public pure nothrow @property @safe @nogc uint air() {
		return _air.value;
	}

	public pure nothrow @property @safe @nogc uint air(uint value) {
		_air.changed = true;
		_air.value = value;
		return value;
	}

	private Changed!(string) _nametag;

	public pure nothrow @property @safe @nogc string nametag() {
		return _nametag.value;
	}

	public pure nothrow @property @safe @nogc string nametag(string value) {
		_nametag.changed = true;
		_nametag.value = value;
		return value;
	}

	private Changed!(bool) _showNametag;

	public pure nothrow @property @safe @nogc bool showNametag() {
		return _showNametag.value;
	}

	public pure nothrow @property @safe @nogc bool showNametag(bool value) {
		_showNametag.changed = true;
		_showNametag.value = value;
		return value;
	}

	private Changed!(bool) _silent;

	public pure nothrow @property @safe @nogc bool silent() {
		return _silent.value;
	}

	public pure nothrow @property @safe @nogc bool silent(bool value) {
		_silent.changed = true;
		_silent.value = value;
		return value;
	}

	private Changed!(bool) _noGravity;

	public pure nothrow @property @safe @nogc bool noGravity() {
		return _noGravity.value;
	}

	public pure nothrow @property @safe @nogc bool noGravity(bool value) {
		_noGravity.changed = true;
		_noGravity.value = value;
		return value;
	}

	private Changed!(sul.protocol.minecraft316.types.Slot) _potion;

	public pure nothrow @property @safe @nogc sul.protocol.minecraft316.types.Slot potion() {
		return _potion.value;
	}

	public pure nothrow @property @safe @nogc sul.protocol.minecraft316.types.Slot potion(sul.protocol.minecraft316.types.Slot value) {
		_potion.changed = true;
		_potion.value = value;
		return value;
	}

	private Changed!(ulong) _spawnPosition;

	public pure nothrow @property @safe @nogc ulong spawnPosition() {
		return _spawnPosition.value;
	}

	public pure nothrow @property @safe @nogc ulong spawnPosition(ulong value) {
		_spawnPosition.changed = true;
		_spawnPosition.value = value;
		return value;
	}

	private Changed!(float) _radius = tuple(cast(float)0.5, false);

	public pure nothrow @property @safe @nogc float radius() {
		return _radius.value;
	}

	public pure nothrow @property @safe @nogc float radius(float value) {
		_radius.changed = true;
		_radius.value = value;
		return value;
	}

	private Changed!(uint) _color = tuple(cast(uint)-1, false);

	public pure nothrow @property @safe @nogc uint color() {
		return _color.value;
	}

	public pure nothrow @property @safe @nogc uint color(uint value) {
		_color.changed = true;
		_color.value = value;
		return value;
	}

	private Changed!(bool) _isSinglePoint;

	public pure nothrow @property @safe @nogc bool isSinglePoint() {
		return _isSinglePoint.value;
	}

	public pure nothrow @property @safe @nogc bool isSinglePoint(bool value) {
		_isSinglePoint.changed = true;
		_isSinglePoint.value = value;
		return value;
	}

	private Changed!(uint) _particleId;

	public pure nothrow @property @safe @nogc uint particleId() {
		return _particleId.value;
	}

	public pure nothrow @property @safe @nogc uint particleId(uint value) {
		_particleId.changed = true;
		_particleId.value = value;
		return value;
	}

	private Changed!(uint) _particleParameter1;

	public pure nothrow @property @safe @nogc uint particleParameter1() {
		return _particleParameter1.value;
	}

	public pure nothrow @property @safe @nogc uint particleParameter1(uint value) {
		_particleParameter1.changed = true;
		_particleParameter1.value = value;
		return value;
	}

	private Changed!(uint) _particleParameter2;

	public pure nothrow @property @safe @nogc uint particleParameter2() {
		return _particleParameter2.value;
	}

	public pure nothrow @property @safe @nogc uint particleParameter2(uint value) {
		_particleParameter2.changed = true;
		_particleParameter2.value = value;
		return value;
	}

	private Changed!(uint) _hookedEntity;

	public pure nothrow @property @safe @nogc uint hookedEntity() {
		return _hookedEntity.value;
	}

	public pure nothrow @property @safe @nogc uint hookedEntity(uint value) {
		_hookedEntity.changed = true;
		_hookedEntity.value = value;
		return value;
	}

	private Changed!(byte) _arrowFlags;

	public pure nothrow @property @safe @nogc byte arrowFlags() {
		return _arrowFlags.value;
	}

	public pure nothrow @property @safe @nogc byte arrowFlags(byte value) {
		_arrowFlags.changed = true;
		_arrowFlags.value = value;
		return value;
	}

	public pure nothrow @property @safe @nogc bool critical() {
		return (_arrowFlags.value >>> 0) & 1;
	}

	public pure nothrow @property @safe @nogc bool critical(bool value) {
		_arrowFlags.changed = true;
		if(value) _arrowFlags.value |= (cast(byte)true << 0);
		else _arrowFlags.value &= ~(cast(byte)true << 0);
		return value;
	}

	private Changed!(uint) _timeSinceLastHit;

	public pure nothrow @property @safe @nogc uint timeSinceLastHit() {
		return _timeSinceLastHit.value;
	}

	public pure nothrow @property @safe @nogc uint timeSinceLastHit(uint value) {
		_timeSinceLastHit.changed = true;
		_timeSinceLastHit.value = value;
		return value;
	}

	private Changed!(uint) _forwardDirection = tuple(cast(uint)1, false);

	public pure nothrow @property @safe @nogc uint forwardDirection() {
		return _forwardDirection.value;
	}

	public pure nothrow @property @safe @nogc uint forwardDirection(uint value) {
		_forwardDirection.changed = true;
		_forwardDirection.value = value;
		return value;
	}

	private Changed!(float) _damageTaken = tuple(cast(float)0, false);

	public pure nothrow @property @safe @nogc float damageTaken() {
		return _damageTaken.value;
	}

	public pure nothrow @property @safe @nogc float damageTaken(float value) {
		_damageTaken.changed = true;
		_damageTaken.value = value;
		return value;
	}

	private Changed!(uint) _boatVariant;

	public pure nothrow @property @safe @nogc uint boatVariant() {
		return _boatVariant.value;
	}

	public pure nothrow @property @safe @nogc uint boatVariant(uint value) {
		_boatVariant.changed = true;
		_boatVariant.value = value;
		return value;
	}

	private Changed!(bool) _rightPaddleTurning;

	public pure nothrow @property @safe @nogc bool rightPaddleTurning() {
		return _rightPaddleTurning.value;
	}

	public pure nothrow @property @safe @nogc bool rightPaddleTurning(bool value) {
		_rightPaddleTurning.changed = true;
		_rightPaddleTurning.value = value;
		return value;
	}

	private Changed!(bool) _leftPaddleTurning;

	public pure nothrow @property @safe @nogc bool leftPaddleTurning() {
		return _leftPaddleTurning.value;
	}

	public pure nothrow @property @safe @nogc bool leftPaddleTurning(bool value) {
		_leftPaddleTurning.changed = true;
		_leftPaddleTurning.value = value;
		return value;
	}

	private Changed!(sul.protocol.minecraft316.types.OptionalPosition) _beamTarget;

	public pure nothrow @property @safe @nogc sul.protocol.minecraft316.types.OptionalPosition beamTarget() {
		return _beamTarget.value;
	}

	public pure nothrow @property @safe @nogc sul.protocol.minecraft316.types.OptionalPosition beamTarget(sul.protocol.minecraft316.types.OptionalPosition value) {
		_beamTarget.changed = true;
		_beamTarget.value = value;
		return value;
	}

	private Changed!(bool) _showBottom;

	public pure nothrow @property @safe @nogc bool showBottom() {
		return _showBottom.value;
	}

	public pure nothrow @property @safe @nogc bool showBottom(bool value) {
		_showBottom.changed = true;
		_showBottom.value = value;
		return value;
	}

	private Changed!(sul.protocol.minecraft316.types.Slot) _firework;

	public pure nothrow @property @safe @nogc sul.protocol.minecraft316.types.Slot firework() {
		return _firework.value;
	}

	public pure nothrow @property @safe @nogc sul.protocol.minecraft316.types.Slot firework(sul.protocol.minecraft316.types.Slot value) {
		_firework.changed = true;
		_firework.value = value;
		return value;
	}

	private Changed!(uint) _fireworkThrower;

	public pure nothrow @property @safe @nogc uint fireworkThrower() {
		return _fireworkThrower.value;
	}

	public pure nothrow @property @safe @nogc uint fireworkThrower(uint value) {
		_fireworkThrower.changed = true;
		_fireworkThrower.value = value;
		return value;
	}

	private Changed!(sul.protocol.minecraft316.types.Slot) _item;

	public pure nothrow @property @safe @nogc sul.protocol.minecraft316.types.Slot item() {
		return _item.value;
	}

	public pure nothrow @property @safe @nogc sul.protocol.minecraft316.types.Slot item(sul.protocol.minecraft316.types.Slot value) {
		_item.changed = true;
		_item.value = value;
		return value;
	}

	private Changed!(uint) _rotation;

	public pure nothrow @property @safe @nogc uint rotation() {
		return _rotation.value;
	}

	public pure nothrow @property @safe @nogc uint rotation(uint value) {
		_rotation.changed = true;
		_rotation.value = value;
		return value;
	}

	private Changed!(byte) _livingFlags;

	public pure nothrow @property @safe @nogc byte livingFlags() {
		return _livingFlags.value;
	}

	public pure nothrow @property @safe @nogc byte livingFlags(byte value) {
		_livingFlags.changed = true;
		_livingFlags.value = value;
		return value;
	}

	public pure nothrow @property @safe @nogc bool handActive() {
		return (_livingFlags.value >>> 0) & 1;
	}

	public pure nothrow @property @safe @nogc bool handActive(bool value) {
		_livingFlags.changed = true;
		if(value) _livingFlags.value |= (cast(byte)true << 0);
		else _livingFlags.value &= ~(cast(byte)true << 0);
		return value;
	}

	public pure nothrow @property @safe @nogc bool offhand() {
		return (_livingFlags.value >>> 1) & 1;
	}

	public pure nothrow @property @safe @nogc bool offhand(bool value) {
		_livingFlags.changed = true;
		if(value) _livingFlags.value |= (cast(byte)true << 1);
		else _livingFlags.value &= ~(cast(byte)true << 1);
		return value;
	}

	private Changed!(float) _health = tuple(cast(float)1, false);

	public pure nothrow @property @safe @nogc float health() {
		return _health.value;
	}

	public pure nothrow @property @safe @nogc float health(float value) {
		_health.changed = true;
		_health.value = value;
		return value;
	}

	private Changed!(uint) _potionColor;

	public pure nothrow @property @safe @nogc uint potionColor() {
		return _potionColor.value;
	}

	public pure nothrow @property @safe @nogc uint potionColor(uint value) {
		_potionColor.changed = true;
		_potionColor.value = value;
		return value;
	}

	private Changed!(bool) _potionAmbient;

	public pure nothrow @property @safe @nogc bool potionAmbient() {
		return _potionAmbient.value;
	}

	public pure nothrow @property @safe @nogc bool potionAmbient(bool value) {
		_potionAmbient.changed = true;
		_potionAmbient.value = value;
		return value;
	}

	private Changed!(uint) _arrows;

	public pure nothrow @property @safe @nogc uint arrows() {
		return _arrows.value;
	}

	public pure nothrow @property @safe @nogc uint arrows(uint value) {
		_arrows.changed = true;
		_arrows.value = value;
		return value;
	}

	private Changed!(float) _additionalHearts = tuple(cast(float)0, false);

	public pure nothrow @property @safe @nogc float additionalHearts() {
		return _additionalHearts.value;
	}

	public pure nothrow @property @safe @nogc float additionalHearts(float value) {
		_additionalHearts.changed = true;
		_additionalHearts.value = value;
		return value;
	}

	private Changed!(uint) _score;

	public pure nothrow @property @safe @nogc uint score() {
		return _score.value;
	}

	public pure nothrow @property @safe @nogc uint score(uint value) {
		_score.changed = true;
		_score.value = value;
		return value;
	}

	private Changed!(byte) _skinParts = tuple(cast(byte)0, false);

	public pure nothrow @property @safe @nogc byte skinParts() {
		return _skinParts.value;
	}

	public pure nothrow @property @safe @nogc byte skinParts(byte value) {
		_skinParts.changed = true;
		_skinParts.value = value;
		return value;
	}

	public pure nothrow @property @safe @nogc bool cape() {
		return (_skinParts.value >>> 0) & 1;
	}

	public pure nothrow @property @safe @nogc bool cape(bool value) {
		_skinParts.changed = true;
		if(value) _skinParts.value |= (cast(byte)true << 0);
		else _skinParts.value &= ~(cast(byte)true << 0);
		return value;
	}

	public pure nothrow @property @safe @nogc bool jacket() {
		return (_skinParts.value >>> 1) & 1;
	}

	public pure nothrow @property @safe @nogc bool jacket(bool value) {
		_skinParts.changed = true;
		if(value) _skinParts.value |= (cast(byte)true << 1);
		else _skinParts.value &= ~(cast(byte)true << 1);
		return value;
	}

	public pure nothrow @property @safe @nogc bool leftSleeve() {
		return (_skinParts.value >>> 2) & 1;
	}

	public pure nothrow @property @safe @nogc bool leftSleeve(bool value) {
		_skinParts.changed = true;
		if(value) _skinParts.value |= (cast(byte)true << 2);
		else _skinParts.value &= ~(cast(byte)true << 2);
		return value;
	}

	public pure nothrow @property @safe @nogc bool rightSleeve() {
		return (_skinParts.value >>> 3) & 1;
	}

	public pure nothrow @property @safe @nogc bool rightSleeve(bool value) {
		_skinParts.changed = true;
		if(value) _skinParts.value |= (cast(byte)true << 3);
		else _skinParts.value &= ~(cast(byte)true << 3);
		return value;
	}

	public pure nothrow @property @safe @nogc bool leftPants() {
		return (_skinParts.value >>> 4) & 1;
	}

	public pure nothrow @property @safe @nogc bool leftPants(bool value) {
		_skinParts.changed = true;
		if(value) _skinParts.value |= (cast(byte)true << 4);
		else _skinParts.value &= ~(cast(byte)true << 4);
		return value;
	}

	public pure nothrow @property @safe @nogc bool rightPants() {
		return (_skinParts.value >>> 5) & 1;
	}

	public pure nothrow @property @safe @nogc bool rightPants(bool value) {
		_skinParts.changed = true;
		if(value) _skinParts.value |= (cast(byte)true << 5);
		else _skinParts.value &= ~(cast(byte)true << 5);
		return value;
	}

	public pure nothrow @property @safe @nogc bool hat() {
		return (_skinParts.value >>> 6) & 1;
	}

	public pure nothrow @property @safe @nogc bool hat(bool value) {
		_skinParts.changed = true;
		if(value) _skinParts.value |= (cast(byte)true << 6);
		else _skinParts.value &= ~(cast(byte)true << 6);
		return value;
	}

	private Changed!(byte) _mainHand = tuple(cast(byte)1, false);

	public pure nothrow @property @safe @nogc byte mainHand() {
		return _mainHand.value;
	}

	public pure nothrow @property @safe @nogc byte mainHand(byte value) {
		_mainHand.changed = true;
		_mainHand.value = value;
		return value;
	}

	private Changed!(byte) _armorStandFlags;

	public pure nothrow @property @safe @nogc byte armorStandFlags() {
		return _armorStandFlags.value;
	}

	public pure nothrow @property @safe @nogc byte armorStandFlags(byte value) {
		_armorStandFlags.changed = true;
		_armorStandFlags.value = value;
		return value;
	}

	public pure nothrow @property @safe @nogc bool isSmall() {
		return (_armorStandFlags.value >>> 0) & 1;
	}

	public pure nothrow @property @safe @nogc bool isSmall(bool value) {
		_armorStandFlags.changed = true;
		if(value) _armorStandFlags.value |= (cast(byte)true << 0);
		else _armorStandFlags.value &= ~(cast(byte)true << 0);
		return value;
	}

	public pure nothrow @property @safe @nogc bool hasArms() {
		return (_armorStandFlags.value >>> 2) & 1;
	}

	public pure nothrow @property @safe @nogc bool hasArms(bool value) {
		_armorStandFlags.changed = true;
		if(value) _armorStandFlags.value |= (cast(byte)true << 2);
		else _armorStandFlags.value &= ~(cast(byte)true << 2);
		return value;
	}

	public pure nothrow @property @safe @nogc bool noBasePlate() {
		return (_armorStandFlags.value >>> 3) & 1;
	}

	public pure nothrow @property @safe @nogc bool noBasePlate(bool value) {
		_armorStandFlags.changed = true;
		if(value) _armorStandFlags.value |= (cast(byte)true << 3);
		else _armorStandFlags.value &= ~(cast(byte)true << 3);
		return value;
	}

	public pure nothrow @property @safe @nogc bool setMarker() {
		return (_armorStandFlags.value >>> 4) & 1;
	}

	public pure nothrow @property @safe @nogc bool setMarker(bool value) {
		_armorStandFlags.changed = true;
		if(value) _armorStandFlags.value |= (cast(byte)true << 4);
		else _armorStandFlags.value &= ~(cast(byte)true << 4);
		return value;
	}

	private Changed!(Tuple!(float, "x", float, "y", float, "z")) _headRotation;

	public pure nothrow @property @safe @nogc Tuple!(float, "x", float, "y", float, "z") headRotation() {
		return _headRotation.value;
	}

	public pure nothrow @property @safe @nogc Tuple!(float, "x", float, "y", float, "z") headRotation(Tuple!(float, "x", float, "y", float, "z") value) {
		_headRotation.changed = true;
		_headRotation.value = value;
		return value;
	}

	private Changed!(Tuple!(float, "x", float, "y", float, "z")) _bodyRotation;

	public pure nothrow @property @safe @nogc Tuple!(float, "x", float, "y", float, "z") bodyRotation() {
		return _bodyRotation.value;
	}

	public pure nothrow @property @safe @nogc Tuple!(float, "x", float, "y", float, "z") bodyRotation(Tuple!(float, "x", float, "y", float, "z") value) {
		_bodyRotation.changed = true;
		_bodyRotation.value = value;
		return value;
	}

	private Changed!(Tuple!(float, "x", float, "y", float, "z")) _leftArmRotation;

	public pure nothrow @property @safe @nogc Tuple!(float, "x", float, "y", float, "z") leftArmRotation() {
		return _leftArmRotation.value;
	}

	public pure nothrow @property @safe @nogc Tuple!(float, "x", float, "y", float, "z") leftArmRotation(Tuple!(float, "x", float, "y", float, "z") value) {
		_leftArmRotation.changed = true;
		_leftArmRotation.value = value;
		return value;
	}

	private Changed!(Tuple!(float, "x", float, "y", float, "z")) _rightArmRotation;

	public pure nothrow @property @safe @nogc Tuple!(float, "x", float, "y", float, "z") rightArmRotation() {
		return _rightArmRotation.value;
	}

	public pure nothrow @property @safe @nogc Tuple!(float, "x", float, "y", float, "z") rightArmRotation(Tuple!(float, "x", float, "y", float, "z") value) {
		_rightArmRotation.changed = true;
		_rightArmRotation.value = value;
		return value;
	}

	private Changed!(Tuple!(float, "x", float, "y", float, "z")) _leftLegRotation;

	public pure nothrow @property @safe @nogc Tuple!(float, "x", float, "y", float, "z") leftLegRotation() {
		return _leftLegRotation.value;
	}

	public pure nothrow @property @safe @nogc Tuple!(float, "x", float, "y", float, "z") leftLegRotation(Tuple!(float, "x", float, "y", float, "z") value) {
		_leftLegRotation.changed = true;
		_leftLegRotation.value = value;
		return value;
	}

	private Changed!(Tuple!(float, "x", float, "y", float, "z")) _rightLegRotation;

	public pure nothrow @property @safe @nogc Tuple!(float, "x", float, "y", float, "z") rightLegRotation() {
		return _rightLegRotation.value;
	}

	public pure nothrow @property @safe @nogc Tuple!(float, "x", float, "y", float, "z") rightLegRotation(Tuple!(float, "x", float, "y", float, "z") value) {
		_rightLegRotation.changed = true;
		_rightLegRotation.value = value;
		return value;
	}

	private Changed!(byte) _instentientFlags;

	public pure nothrow @property @safe @nogc byte instentientFlags() {
		return _instentientFlags.value;
	}

	public pure nothrow @property @safe @nogc byte instentientFlags(byte value) {
		_instentientFlags.changed = true;
		_instentientFlags.value = value;
		return value;
	}

	public pure nothrow @property @safe @nogc bool noAi() {
		return (_instentientFlags.value >>> 0) & 1;
	}

	public pure nothrow @property @safe @nogc bool noAi(bool value) {
		_instentientFlags.changed = true;
		if(value) _instentientFlags.value |= (cast(byte)true << 0);
		else _instentientFlags.value &= ~(cast(byte)true << 0);
		return value;
	}

	public pure nothrow @property @safe @nogc bool leftHanded() {
		return (_instentientFlags.value >>> 1) & 1;
	}

	public pure nothrow @property @safe @nogc bool leftHanded(bool value) {
		_instentientFlags.changed = true;
		if(value) _instentientFlags.value |= (cast(byte)true << 1);
		else _instentientFlags.value &= ~(cast(byte)true << 1);
		return value;
	}

	private Changed!(byte) _hanging;

	public pure nothrow @property @safe @nogc byte hanging() {
		return _hanging.value;
	}

	public pure nothrow @property @safe @nogc byte hanging(byte value) {
		_hanging.changed = true;
		_hanging.value = value;
		return value;
	}

	private Changed!(bool) _baby;

	public pure nothrow @property @safe @nogc bool baby() {
		return _baby.value;
	}

	public pure nothrow @property @safe @nogc bool baby(bool value) {
		_baby.changed = true;
		_baby.value = value;
		return value;
	}

	private Changed!(byte) _horseFlags;

	public pure nothrow @property @safe @nogc byte horseFlags() {
		return _horseFlags.value;
	}

	public pure nothrow @property @safe @nogc byte horseFlags(byte value) {
		_horseFlags.changed = true;
		_horseFlags.value = value;
		return value;
	}

	public pure nothrow @property @safe @nogc bool horseTamed() {
		return (_horseFlags.value >>> 1) & 1;
	}

	public pure nothrow @property @safe @nogc bool horseTamed(bool value) {
		_horseFlags.changed = true;
		if(value) _horseFlags.value |= (cast(byte)true << 1);
		else _horseFlags.value &= ~(cast(byte)true << 1);
		return value;
	}

	public pure nothrow @property @safe @nogc bool horseSaddled() {
		return (_horseFlags.value >>> 2) & 1;
	}

	public pure nothrow @property @safe @nogc bool horseSaddled(bool value) {
		_horseFlags.changed = true;
		if(value) _horseFlags.value |= (cast(byte)true << 2);
		else _horseFlags.value &= ~(cast(byte)true << 2);
		return value;
	}

	public pure nothrow @property @safe @nogc bool horseChested() {
		return (_horseFlags.value >>> 3) & 1;
	}

	public pure nothrow @property @safe @nogc bool horseChested(bool value) {
		_horseFlags.changed = true;
		if(value) _horseFlags.value |= (cast(byte)true << 3);
		else _horseFlags.value &= ~(cast(byte)true << 3);
		return value;
	}

	public pure nothrow @property @safe @nogc bool horseEating() {
		return (_horseFlags.value >>> 5) & 1;
	}

	public pure nothrow @property @safe @nogc bool horseEating(bool value) {
		_horseFlags.changed = true;
		if(value) _horseFlags.value |= (cast(byte)true << 5);
		else _horseFlags.value &= ~(cast(byte)true << 5);
		return value;
	}

	public pure nothrow @property @safe @nogc bool horseRearing() {
		return (_horseFlags.value >>> 6) & 1;
	}

	public pure nothrow @property @safe @nogc bool horseRearing(bool value) {
		_horseFlags.changed = true;
		if(value) _horseFlags.value |= (cast(byte)true << 6);
		else _horseFlags.value &= ~(cast(byte)true << 6);
		return value;
	}

	public pure nothrow @property @safe @nogc bool mouthOpen() {
		return (_horseFlags.value >>> 7) & 1;
	}

	public pure nothrow @property @safe @nogc bool mouthOpen(bool value) {
		_horseFlags.changed = true;
		if(value) _horseFlags.value |= (cast(byte)true << 7);
		else _horseFlags.value &= ~(cast(byte)true << 7);
		return value;
	}

	private Changed!(sul.protocol.minecraft316.types.OptionalUuid) _ownerUuid;

	public pure nothrow @property @safe @nogc sul.protocol.minecraft316.types.OptionalUuid ownerUuid() {
		return _ownerUuid.value;
	}

	public pure nothrow @property @safe @nogc sul.protocol.minecraft316.types.OptionalUuid ownerUuid(sul.protocol.minecraft316.types.OptionalUuid value) {
		_ownerUuid.changed = true;
		_ownerUuid.value = value;
		return value;
	}

	private Changed!(uint) _horseVariant;

	public pure nothrow @property @safe @nogc uint horseVariant() {
		return _horseVariant.value;
	}

	public pure nothrow @property @safe @nogc uint horseVariant(uint value) {
		_horseVariant.changed = true;
		_horseVariant.value = value;
		return value;
	}

	private Changed!(uint) _horseArmor;

	public pure nothrow @property @safe @nogc uint horseArmor() {
		return _horseArmor.value;
	}

	public pure nothrow @property @safe @nogc uint horseArmor(uint value) {
		_horseArmor.changed = true;
		_horseArmor.value = value;
		return value;
	}

	private Changed!(bool) _chested;

	public pure nothrow @property @safe @nogc bool chested() {
		return _chested.value;
	}

	public pure nothrow @property @safe @nogc bool chested(bool value) {
		_chested.changed = true;
		_chested.value = value;
		return value;
	}

	private Changed!(uint) _llamaStrength;

	public pure nothrow @property @safe @nogc uint llamaStrength() {
		return _llamaStrength.value;
	}

	public pure nothrow @property @safe @nogc uint llamaStrength(uint value) {
		_llamaStrength.changed = true;
		_llamaStrength.value = value;
		return value;
	}

	private Changed!(uint) _carpetColor = tuple(cast(uint)-1, false);

	public pure nothrow @property @safe @nogc uint carpetColor() {
		return _carpetColor.value;
	}

	public pure nothrow @property @safe @nogc uint carpetColor(uint value) {
		_carpetColor.changed = true;
		_carpetColor.value = value;
		return value;
	}

	private Changed!(uint) _llamaVariant;

	public pure nothrow @property @safe @nogc uint llamaVariant() {
		return _llamaVariant.value;
	}

	public pure nothrow @property @safe @nogc uint llamaVariant(uint value) {
		_llamaVariant.changed = true;
		_llamaVariant.value = value;
		return value;
	}

	private Changed!(bool) _pigSaddled;

	public pure nothrow @property @safe @nogc bool pigSaddled() {
		return _pigSaddled.value;
	}

	public pure nothrow @property @safe @nogc bool pigSaddled(bool value) {
		_pigSaddled.changed = true;
		_pigSaddled.value = value;
		return value;
	}

	private Changed!(uint) _carrotBoost;

	public pure nothrow @property @safe @nogc uint carrotBoost() {
		return _carrotBoost.value;
	}

	public pure nothrow @property @safe @nogc uint carrotBoost(uint value) {
		_carrotBoost.changed = true;
		_carrotBoost.value = value;
		return value;
	}

	private Changed!(uint) _rabbitVariant;

	public pure nothrow @property @safe @nogc uint rabbitVariant() {
		return _rabbitVariant.value;
	}

	public pure nothrow @property @safe @nogc uint rabbitVariant(uint value) {
		_rabbitVariant.changed = true;
		_rabbitVariant.value = value;
		return value;
	}

	private Changed!(bool) _standingUp;

	public pure nothrow @property @safe @nogc bool standingUp() {
		return _standingUp.value;
	}

	public pure nothrow @property @safe @nogc bool standingUp(bool value) {
		_standingUp.changed = true;
		_standingUp.value = value;
		return value;
	}

	private Changed!(byte) _sheepFlagsAndColor;

	public pure nothrow @property @safe @nogc byte sheepFlagsAndColor() {
		return _sheepFlagsAndColor.value;
	}

	public pure nothrow @property @safe @nogc byte sheepFlagsAndColor(byte value) {
		_sheepFlagsAndColor.changed = true;
		_sheepFlagsAndColor.value = value;
		return value;
	}

	public pure nothrow @property @safe @nogc bool sheared() {
		return (_sheepFlagsAndColor.value >>> 7) & 1;
	}

	public pure nothrow @property @safe @nogc bool sheared(bool value) {
		_sheepFlagsAndColor.changed = true;
		if(value) _sheepFlagsAndColor.value |= (cast(byte)true << 7);
		else _sheepFlagsAndColor.value &= ~(cast(byte)true << 7);
		return value;
	}

	private Changed!(byte) _tameableFlags;

	public pure nothrow @property @safe @nogc byte tameableFlags() {
		return _tameableFlags.value;
	}

	public pure nothrow @property @safe @nogc byte tameableFlags(byte value) {
		_tameableFlags.changed = true;
		_tameableFlags.value = value;
		return value;
	}

	public pure nothrow @property @safe @nogc bool sitting() {
		return (_tameableFlags.value >>> 0) & 1;
	}

	public pure nothrow @property @safe @nogc bool sitting(bool value) {
		_tameableFlags.changed = true;
		if(value) _tameableFlags.value |= (cast(byte)true << 0);
		else _tameableFlags.value &= ~(cast(byte)true << 0);
		return value;
	}

	public pure nothrow @property @safe @nogc bool angry() {
		return (_tameableFlags.value >>> 1) & 1;
	}

	public pure nothrow @property @safe @nogc bool angry(bool value) {
		_tameableFlags.changed = true;
		if(value) _tameableFlags.value |= (cast(byte)true << 1);
		else _tameableFlags.value &= ~(cast(byte)true << 1);
		return value;
	}

	public pure nothrow @property @safe @nogc bool tamed() {
		return (_tameableFlags.value >>> 2) & 1;
	}

	public pure nothrow @property @safe @nogc bool tamed(bool value) {
		_tameableFlags.changed = true;
		if(value) _tameableFlags.value |= (cast(byte)true << 2);
		else _tameableFlags.value &= ~(cast(byte)true << 2);
		return value;
	}

	private Changed!(uint) _ocelotVariant;

	public pure nothrow @property @safe @nogc uint ocelotVariant() {
		return _ocelotVariant.value;
	}

	public pure nothrow @property @safe @nogc uint ocelotVariant(uint value) {
		_ocelotVariant.changed = true;
		_ocelotVariant.value = value;
		return value;
	}

	private Changed!(float) _wolfHealth;

	public pure nothrow @property @safe @nogc float wolfHealth() {
		return _wolfHealth.value;
	}

	public pure nothrow @property @safe @nogc float wolfHealth(float value) {
		_wolfHealth.changed = true;
		_wolfHealth.value = value;
		return value;
	}

	private Changed!(bool) _begging;

	public pure nothrow @property @safe @nogc bool begging() {
		return _begging.value;
	}

	public pure nothrow @property @safe @nogc bool begging(bool value) {
		_begging.changed = true;
		_begging.value = value;
		return value;
	}

	private Changed!(uint) _collarColor = tuple(cast(uint)14, false);

	public pure nothrow @property @safe @nogc uint collarColor() {
		return _collarColor.value;
	}

	public pure nothrow @property @safe @nogc uint collarColor(uint value) {
		_collarColor.changed = true;
		_collarColor.value = value;
		return value;
	}

	private Changed!(uint) _profession;

	public pure nothrow @property @safe @nogc uint profession() {
		return _profession.value;
	}

	public pure nothrow @property @safe @nogc uint profession(uint value) {
		_profession.changed = true;
		_profession.value = value;
		return value;
	}

	private Changed!(byte) _createdByPlayer;

	public pure nothrow @property @safe @nogc byte createdByPlayer() {
		return _createdByPlayer.value;
	}

	public pure nothrow @property @safe @nogc byte createdByPlayer(byte value) {
		_createdByPlayer.changed = true;
		_createdByPlayer.value = value;
		return value;
	}

	private Changed!(byte) _snowmanFlags;

	public pure nothrow @property @safe @nogc byte snowmanFlags() {
		return _snowmanFlags.value;
	}

	public pure nothrow @property @safe @nogc byte snowmanFlags(byte value) {
		_snowmanFlags.changed = true;
		_snowmanFlags.value = value;
		return value;
	}

	public pure nothrow @property @safe @nogc bool pumpkinless() {
		return (_snowmanFlags.value >>> 4) & 1;
	}

	public pure nothrow @property @safe @nogc bool pumpkinless(bool value) {
		_snowmanFlags.changed = true;
		if(value) _snowmanFlags.value |= (cast(byte)true << 4);
		else _snowmanFlags.value &= ~(cast(byte)true << 4);
		return value;
	}

	private Changed!(uint) _shulkerDirection;

	public pure nothrow @property @safe @nogc uint shulkerDirection() {
		return _shulkerDirection.value;
	}

	public pure nothrow @property @safe @nogc uint shulkerDirection(uint value) {
		_shulkerDirection.changed = true;
		_shulkerDirection.value = value;
		return value;
	}

	private Changed!(sul.protocol.minecraft316.types.OptionalPosition) _shulkerAttachment;

	public pure nothrow @property @safe @nogc sul.protocol.minecraft316.types.OptionalPosition shulkerAttachment() {
		return _shulkerAttachment.value;
	}

	public pure nothrow @property @safe @nogc sul.protocol.minecraft316.types.OptionalPosition shulkerAttachment(sul.protocol.minecraft316.types.OptionalPosition value) {
		_shulkerAttachment.changed = true;
		_shulkerAttachment.value = value;
		return value;
	}

	private Changed!(byte) _shulkerShieldHeight;

	public pure nothrow @property @safe @nogc byte shulkerShieldHeight() {
		return _shulkerShieldHeight.value;
	}

	public pure nothrow @property @safe @nogc byte shulkerShieldHeight(byte value) {
		_shulkerShieldHeight.changed = true;
		_shulkerShieldHeight.value = value;
		return value;
	}

	private Changed!(byte) _shulkerColor;

	public pure nothrow @property @safe @nogc byte shulkerColor() {
		return _shulkerColor.value;
	}

	public pure nothrow @property @safe @nogc byte shulkerColor(byte value) {
		_shulkerColor.changed = true;
		_shulkerColor.value = value;
		return value;
	}

	private Changed!(byte) _blazeOnFire;

	public pure nothrow @property @safe @nogc byte blazeOnFire() {
		return _blazeOnFire.value;
	}

	public pure nothrow @property @safe @nogc byte blazeOnFire(byte value) {
		_blazeOnFire.changed = true;
		_blazeOnFire.value = value;
		return value;
	}

	private Changed!(uint) _creeperState = tuple(cast(uint)-1, false);

	public pure nothrow @property @safe @nogc uint creeperState() {
		return _creeperState.value;
	}

	public pure nothrow @property @safe @nogc uint creeperState(uint value) {
		_creeperState.changed = true;
		_creeperState.value = value;
		return value;
	}

	private Changed!(bool) _charged;

	public pure nothrow @property @safe @nogc bool charged() {
		return _charged.value;
	}

	public pure nothrow @property @safe @nogc bool charged(bool value) {
		_charged.changed = true;
		_charged.value = value;
		return value;
	}

	private Changed!(bool) _ignited;

	public pure nothrow @property @safe @nogc bool ignited() {
		return _ignited.value;
	}

	public pure nothrow @property @safe @nogc bool ignited(bool value) {
		_ignited.changed = true;
		_ignited.value = value;
		return value;
	}

	private Changed!(bool) _rectractingSpikes;

	public pure nothrow @property @safe @nogc bool rectractingSpikes() {
		return _rectractingSpikes.value;
	}

	public pure nothrow @property @safe @nogc bool rectractingSpikes(bool value) {
		_rectractingSpikes.changed = true;
		_rectractingSpikes.value = value;
		return value;
	}

	private Changed!(uint) _guardianTarget;

	public pure nothrow @property @safe @nogc uint guardianTarget() {
		return _guardianTarget.value;
	}

	public pure nothrow @property @safe @nogc uint guardianTarget(uint value) {
		_guardianTarget.changed = true;
		_guardianTarget.value = value;
		return value;
	}

	private Changed!(byte) _spell;

	public pure nothrow @property @safe @nogc byte spell() {
		return _spell.value;
	}

	public pure nothrow @property @safe @nogc byte spell(byte value) {
		_spell.changed = true;
		_spell.value = value;
		return value;
	}

	private Changed!(byte) _attackMode;

	public pure nothrow @property @safe @nogc byte attackMode() {
		return _attackMode.value;
	}

	public pure nothrow @property @safe @nogc byte attackMode(byte value) {
		_attackMode.changed = true;
		_attackMode.value = value;
		return value;
	}

	private Changed!(bool) _swingingArms;

	public pure nothrow @property @safe @nogc bool swingingArms() {
		return _swingingArms.value;
	}

	public pure nothrow @property @safe @nogc bool swingingArms(bool value) {
		_swingingArms.changed = true;
		_swingingArms.value = value;
		return value;
	}

	private Changed!(byte) _climbing;

	public pure nothrow @property @safe @nogc byte climbing() {
		return _climbing.value;
	}

	public pure nothrow @property @safe @nogc byte climbing(byte value) {
		_climbing.changed = true;
		_climbing.value = value;
		return value;
	}

	private Changed!(uint) _centerHeadTarget;

	public pure nothrow @property @safe @nogc uint centerHeadTarget() {
		return _centerHeadTarget.value;
	}

	public pure nothrow @property @safe @nogc uint centerHeadTarget(uint value) {
		_centerHeadTarget.changed = true;
		_centerHeadTarget.value = value;
		return value;
	}

	private Changed!(uint) _leftHeadTarget;

	public pure nothrow @property @safe @nogc uint leftHeadTarget() {
		return _leftHeadTarget.value;
	}

	public pure nothrow @property @safe @nogc uint leftHeadTarget(uint value) {
		_leftHeadTarget.changed = true;
		_leftHeadTarget.value = value;
		return value;
	}

	private Changed!(uint) _rightHeadTarget;

	public pure nothrow @property @safe @nogc uint rightHeadTarget() {
		return _rightHeadTarget.value;
	}

	public pure nothrow @property @safe @nogc uint rightHeadTarget(uint value) {
		_rightHeadTarget.changed = true;
		_rightHeadTarget.value = value;
		return value;
	}

	private Changed!(uint) _invulnerableTime;

	public pure nothrow @property @safe @nogc uint invulnerableTime() {
		return _invulnerableTime.value;
	}

	public pure nothrow @property @safe @nogc uint invulnerableTime(uint value) {
		_invulnerableTime.changed = true;
		_invulnerableTime.value = value;
		return value;
	}

	private Changed!(bool) _handsHeldUp;

	public pure nothrow @property @safe @nogc bool handsHeldUp() {
		return _handsHeldUp.value;
	}

	public pure nothrow @property @safe @nogc bool handsHeldUp(bool value) {
		_handsHeldUp.changed = true;
		_handsHeldUp.value = value;
		return value;
	}

	private Changed!(bool) _converting;

	public pure nothrow @property @safe @nogc bool converting() {
		return _converting.value;
	}

	public pure nothrow @property @safe @nogc bool converting(bool value) {
		_converting.changed = true;
		_converting.value = value;
		return value;
	}

	private Changed!(uint) _zombieVillagerProfession;

	public pure nothrow @property @safe @nogc uint zombieVillagerProfession() {
		return _zombieVillagerProfession.value;
	}

	public pure nothrow @property @safe @nogc uint zombieVillagerProfession(uint value) {
		_zombieVillagerProfession.changed = true;
		_zombieVillagerProfession.value = value;
		return value;
	}

	private Changed!(uint) _carriedBlock;

	public pure nothrow @property @safe @nogc uint carriedBlock() {
		return _carriedBlock.value;
	}

	public pure nothrow @property @safe @nogc uint carriedBlock(uint value) {
		_carriedBlock.changed = true;
		_carriedBlock.value = value;
		return value;
	}

	private Changed!(bool) _screaming;

	public pure nothrow @property @safe @nogc bool screaming() {
		return _screaming.value;
	}

	public pure nothrow @property @safe @nogc bool screaming(bool value) {
		_screaming.changed = true;
		_screaming.value = value;
		return value;
	}

	private Changed!(uint) _dragonPhase;

	public pure nothrow @property @safe @nogc uint dragonPhase() {
		return _dragonPhase.value;
	}

	public pure nothrow @property @safe @nogc uint dragonPhase(uint value) {
		_dragonPhase.changed = true;
		_dragonPhase.value = value;
		return value;
	}

	private Changed!(bool) _ghastAttacking;

	public pure nothrow @property @safe @nogc bool ghastAttacking() {
		return _ghastAttacking.value;
	}

	public pure nothrow @property @safe @nogc bool ghastAttacking(bool value) {
		_ghastAttacking.changed = true;
		_ghastAttacking.value = value;
		return value;
	}

	private Changed!(uint) _slimeSize = tuple(cast(uint)1, false);

	public pure nothrow @property @safe @nogc uint slimeSize() {
		return _slimeSize.value;
	}

	public pure nothrow @property @safe @nogc uint slimeSize(uint value) {
		_slimeSize.changed = true;
		_slimeSize.value = value;
		return value;
	}

	private Changed!(uint) _shakingPower;

	public pure nothrow @property @safe @nogc uint shakingPower() {
		return _shakingPower.value;
	}

	public pure nothrow @property @safe @nogc uint shakingPower(uint value) {
		_shakingPower.changed = true;
		_shakingPower.value = value;
		return value;
	}

	private Changed!(uint) _shakingDirection;

	public pure nothrow @property @safe @nogc uint shakingDirection() {
		return _shakingDirection.value;
	}

	public pure nothrow @property @safe @nogc uint shakingDirection(uint value) {
		_shakingDirection.changed = true;
		_shakingDirection.value = value;
		return value;
	}

	private Changed!(float) _shakingMultiplier = tuple(cast(float)0, false);

	public pure nothrow @property @safe @nogc float shakingMultiplier() {
		return _shakingMultiplier.value;
	}

	public pure nothrow @property @safe @nogc float shakingMultiplier(float value) {
		_shakingMultiplier.changed = true;
		_shakingMultiplier.value = value;
		return value;
	}

	private Changed!(uint) _minecartBlock;

	public pure nothrow @property @safe @nogc uint minecartBlock() {
		return _minecartBlock.value;
	}

	public pure nothrow @property @safe @nogc uint minecartBlock(uint value) {
		_minecartBlock.changed = true;
		_minecartBlock.value = value;
		return value;
	}

	private Changed!(uint) _minecartBlockPosition = tuple(cast(uint)6, false);

	public pure nothrow @property @safe @nogc uint minecartBlockPosition() {
		return _minecartBlockPosition.value;
	}

	public pure nothrow @property @safe @nogc uint minecartBlockPosition(uint value) {
		_minecartBlockPosition.changed = true;
		_minecartBlockPosition.value = value;
		return value;
	}

	private Changed!(bool) _minecartCustomBlock;

	public pure nothrow @property @safe @nogc bool minecartCustomBlock() {
		return _minecartCustomBlock.value;
	}

	public pure nothrow @property @safe @nogc bool minecartCustomBlock(bool value) {
		_minecartCustomBlock.changed = true;
		_minecartCustomBlock.value = value;
		return value;
	}

	private Changed!(bool) _furnacePowered;

	public pure nothrow @property @safe @nogc bool furnacePowered() {
		return _furnacePowered.value;
	}

	public pure nothrow @property @safe @nogc bool furnacePowered(bool value) {
		_furnacePowered.changed = true;
		_furnacePowered.value = value;
		return value;
	}

	private Changed!(string) _command;

	public pure nothrow @property @safe @nogc string command() {
		return _command.value;
	}

	public pure nothrow @property @safe @nogc string command(string value) {
		_command.changed = true;
		_command.value = value;
		return value;
	}

	private Changed!(string) _lastOutput;

	public pure nothrow @property @safe @nogc string lastOutput() {
		return _lastOutput.value;
	}

	public pure nothrow @property @safe @nogc string lastOutput(string value) {
		_lastOutput.changed = true;
		_lastOutput.value = value;
		return value;
	}

	private Changed!(uint) _fuseTime;

	public pure nothrow @property @safe @nogc uint fuseTime() {
		return _fuseTime.value;
	}

	public pure nothrow @property @safe @nogc uint fuseTime(uint value) {
		_fuseTime.changed = true;
		_fuseTime.value = value;
		return value;
	}

	public pure nothrow @safe encode(Buffer buffer) {
		with(buffer) {
			{ writeBigEndianByte(entityFlags); }
			if(this._air.changed){ writeBytes(varuint.encode(air)); }
			if(this._nametag.changed){ writeBytes(varuint.encode(cast(uint)nametag.length)); writeString(nametag); }
			if(this._showNametag.changed){ writeBigEndianBool(showNametag); }
			if(this._silent.changed){ writeBigEndianBool(silent); }
			if(this._noGravity.changed){ writeBigEndianBool(noGravity); }
			if(this._potion.changed){ potion.encode(bufferInstance); }
			if(this._spawnPosition.changed){ writeBigEndianUlong(spawnPosition); }
			if(this._radius.changed){ writeBigEndianFloat(radius); }
			if(this._color.changed){ writeBytes(varuint.encode(color)); }
			if(this._isSinglePoint.changed){ writeBigEndianBool(isSinglePoint); }
			if(this._particleId.changed){ writeBytes(varuint.encode(particleId)); }
			if(this._particleParameter1.changed){ writeBytes(varuint.encode(particleParameter1)); }
			if(this._particleParameter2.changed){ writeBytes(varuint.encode(particleParameter2)); }
			if(this._hookedEntity.changed){ writeBytes(varuint.encode(hookedEntity)); }
			if(this._arrowFlags.changed){ writeBigEndianByte(arrowFlags); }
			if(this._timeSinceLastHit.changed){ writeBytes(varuint.encode(timeSinceLastHit)); }
			if(this._forwardDirection.changed){ writeBytes(varuint.encode(forwardDirection)); }
			if(this._damageTaken.changed){ writeBigEndianFloat(damageTaken); }
			if(this._boatVariant.changed){ writeBytes(varuint.encode(boatVariant)); }
			if(this._rightPaddleTurning.changed){ writeBigEndianBool(rightPaddleTurning); }
			if(this._leftPaddleTurning.changed){ writeBigEndianBool(leftPaddleTurning); }
			if(this._beamTarget.changed){ beamTarget.encode(bufferInstance); }
			if(this._showBottom.changed){ writeBigEndianBool(showBottom); }
			if(this._firework.changed){ firework.encode(bufferInstance); }
			if(this._fireworkThrower.changed){ writeBytes(varuint.encode(fireworkThrower)); }
			if(this._item.changed){ item.encode(bufferInstance); }
			if(this._rotation.changed){ writeBytes(varuint.encode(rotation)); }
			if(this._livingFlags.changed){ writeBigEndianByte(livingFlags); }
			if(this._health.changed){ writeBigEndianFloat(health); }
			if(this._potionColor.changed){ writeBytes(varuint.encode(potionColor)); }
			if(this._potionAmbient.changed){ writeBigEndianBool(potionAmbient); }
			if(this._arrows.changed){ writeBytes(varuint.encode(arrows)); }
			if(this._additionalHearts.changed){ writeBigEndianFloat(additionalHearts); }
			if(this._score.changed){ writeBytes(varuint.encode(score)); }
			if(this._skinParts.changed){ writeBigEndianByte(skinParts); }
			if(this._mainHand.changed){ writeBigEndianByte(mainHand); }
			if(this._armorStandFlags.changed){ writeBigEndianByte(armorStandFlags); }
			if(this._headRotation.changed){ writeBigEndianFloat(headRotation.x); writeBigEndianFloat(headRotation.y); writeBigEndianFloat(headRotation.z); }
			if(this._bodyRotation.changed){ writeBigEndianFloat(bodyRotation.x); writeBigEndianFloat(bodyRotation.y); writeBigEndianFloat(bodyRotation.z); }
			if(this._leftArmRotation.changed){ writeBigEndianFloat(leftArmRotation.x); writeBigEndianFloat(leftArmRotation.y); writeBigEndianFloat(leftArmRotation.z); }
			if(this._rightArmRotation.changed){ writeBigEndianFloat(rightArmRotation.x); writeBigEndianFloat(rightArmRotation.y); writeBigEndianFloat(rightArmRotation.z); }
			if(this._leftLegRotation.changed){ writeBigEndianFloat(leftLegRotation.x); writeBigEndianFloat(leftLegRotation.y); writeBigEndianFloat(leftLegRotation.z); }
			if(this._rightLegRotation.changed){ writeBigEndianFloat(rightLegRotation.x); writeBigEndianFloat(rightLegRotation.y); writeBigEndianFloat(rightLegRotation.z); }
			if(this._instentientFlags.changed){ writeBigEndianByte(instentientFlags); }
			if(this._hanging.changed){ writeBigEndianByte(hanging); }
			if(this._baby.changed){ writeBigEndianBool(baby); }
			if(this._horseFlags.changed){ writeBigEndianByte(horseFlags); }
			if(this._ownerUuid.changed){ ownerUuid.encode(bufferInstance); }
			if(this._horseVariant.changed){ writeBytes(varuint.encode(horseVariant)); }
			if(this._horseArmor.changed){ writeBytes(varuint.encode(horseArmor)); }
			if(this._chested.changed){ writeBigEndianBool(chested); }
			if(this._llamaStrength.changed){ writeBytes(varuint.encode(llamaStrength)); }
			if(this._carpetColor.changed){ writeBytes(varuint.encode(carpetColor)); }
			if(this._llamaVariant.changed){ writeBytes(varuint.encode(llamaVariant)); }
			if(this._pigSaddled.changed){ writeBigEndianBool(pigSaddled); }
			if(this._carrotBoost.changed){ writeBytes(varuint.encode(carrotBoost)); }
			if(this._rabbitVariant.changed){ writeBytes(varuint.encode(rabbitVariant)); }
			if(this._standingUp.changed){ writeBigEndianBool(standingUp); }
			if(this._sheepFlagsAndColor.changed){ writeBigEndianByte(sheepFlagsAndColor); }
			if(this._tameableFlags.changed){ writeBigEndianByte(tameableFlags); }
			if(this._ocelotVariant.changed){ writeBytes(varuint.encode(ocelotVariant)); }
			if(this._wolfHealth.changed){ writeBigEndianFloat(wolfHealth); }
			if(this._begging.changed){ writeBigEndianBool(begging); }
			if(this._collarColor.changed){ writeBytes(varuint.encode(collarColor)); }
			if(this._profession.changed){ writeBytes(varuint.encode(profession)); }
			if(this._createdByPlayer.changed){ writeBigEndianByte(createdByPlayer); }
			if(this._snowmanFlags.changed){ writeBigEndianByte(snowmanFlags); }
			if(this._shulkerDirection.changed){ writeBytes(varuint.encode(shulkerDirection)); }
			if(this._shulkerAttachment.changed){ shulkerAttachment.encode(bufferInstance); }
			if(this._shulkerShieldHeight.changed){ writeBigEndianByte(shulkerShieldHeight); }
			if(this._shulkerColor.changed){ writeBigEndianByte(shulkerColor); }
			if(this._blazeOnFire.changed){ writeBigEndianByte(blazeOnFire); }
			if(this._creeperState.changed){ writeBytes(varuint.encode(creeperState)); }
			if(this._charged.changed){ writeBigEndianBool(charged); }
			if(this._ignited.changed){ writeBigEndianBool(ignited); }
			if(this._rectractingSpikes.changed){ writeBigEndianBool(rectractingSpikes); }
			if(this._guardianTarget.changed){ writeBytes(varuint.encode(guardianTarget)); }
			if(this._spell.changed){ writeBigEndianByte(spell); }
			if(this._attackMode.changed){ writeBigEndianByte(attackMode); }
			if(this._swingingArms.changed){ writeBigEndianBool(swingingArms); }
			if(this._climbing.changed){ writeBigEndianByte(climbing); }
			if(this._centerHeadTarget.changed){ writeBytes(varuint.encode(centerHeadTarget)); }
			if(this._leftHeadTarget.changed){ writeBytes(varuint.encode(leftHeadTarget)); }
			if(this._rightHeadTarget.changed){ writeBytes(varuint.encode(rightHeadTarget)); }
			if(this._invulnerableTime.changed){ writeBytes(varuint.encode(invulnerableTime)); }
			if(this._handsHeldUp.changed){ writeBigEndianBool(handsHeldUp); }
			if(this._converting.changed){ writeBigEndianBool(converting); }
			if(this._zombieVillagerProfession.changed){ writeBytes(varuint.encode(zombieVillagerProfession)); }
			if(this._carriedBlock.changed){ writeBytes(varuint.encode(carriedBlock)); }
			if(this._screaming.changed){ writeBigEndianBool(screaming); }
			if(this._dragonPhase.changed){ writeBytes(varuint.encode(dragonPhase)); }
			if(this._ghastAttacking.changed){ writeBigEndianBool(ghastAttacking); }
			if(this._slimeSize.changed){ writeBytes(varuint.encode(slimeSize)); }
			if(this._shakingPower.changed){ writeBytes(varuint.encode(shakingPower)); }
			if(this._shakingDirection.changed){ writeBytes(varuint.encode(shakingDirection)); }
			if(this._shakingMultiplier.changed){ writeBigEndianFloat(shakingMultiplier); }
			if(this._minecartBlock.changed){ writeBytes(varuint.encode(minecartBlock)); }
			if(this._minecartBlockPosition.changed){ writeBytes(varuint.encode(minecartBlockPosition)); }
			if(this._minecartCustomBlock.changed){ writeBigEndianBool(minecartCustomBlock); }
			if(this._furnacePowered.changed){ writeBigEndianBool(furnacePowered); }
			if(this._command.changed){ writeBytes(varuint.encode(cast(uint)command.length)); writeString(command); }
			if(this._lastOutput.changed){ writeBytes(varuint.encode(cast(uint)lastOutput.length)); writeString(lastOutput); }
			if(this._fuseTime.changed){ writeBytes(varuint.encode(fuseTime)); }
			writeBigEndianUbyte(255);
		}
	}

}
