/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/hncom1.xml
 */
package sul.protocol.hncom1.player;

import java.nio.charset.StandardCharsets;

import sul.utils.*;

/**
 * Updates player's world and dimension.
 */
public class UpdateWorld extends Packet {

	public static final byte ID = (byte)20;

	public static final boolean CLIENTBOUND = false;
	public static final boolean SERVERBOUND = true;

	@Override
	public int getId() {
		return ID;
	}

	public int hubId;

	/**
	 * World's name, used mainly for display purposes.
	 */
	public String world;

	/**
	 * World's dimension, that may differ from Minecraft's version. It's used for synchronise
	 * entities and chunks when changing node as described at Add.dimension.
	 */
	public byte dimension;

	public UpdateWorld() {}

	public UpdateWorld(int hubId, String world, byte dimension) {
		this.hubId = hubId;
		this.world = world;
		this.dimension = dimension;
	}

	@Override
	public int length() {
		return Buffer.varuintLength(hubId) + Buffer.varuintLength(world.getBytes(StandardCharsets.UTF_8).length) + world.getBytes(StandardCharsets.UTF_8).length + 2;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeBigEndianByte(ID);
		this.writeVaruint(hubId);
		byte[] d9bq=world.getBytes(StandardCharsets.UTF_8); this.writeVaruint((int)d9bq.length); this.writeBytes(d9bq);
		this.writeBigEndianByte(dimension);
		return this.getBuffer();
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		readBigEndianByte();
		hubId=this.readVaruint();
		int bvd9bq=this.readVaruint(); world=new String(this.readBytes(bvd9bq), StandardCharsets.UTF_8);
		dimension=readBigEndianByte();
	}

	public static UpdateWorld fromBuffer(byte[] buffer) {
		UpdateWorld ret = new UpdateWorld();
		ret.decode(buffer);
		return ret;
	}

	@Override
	public String toString() {
		return "UpdateWorld(hubId: " + this.hubId + ", world: " + this.world + ", dimension: " + this.dimension + ")";
	}

}
