/*
 * This file has been automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 *
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generator: https://github.com/sel-project/sel-utils/blob/master/xml/protocol/minecraft107.xml
 */
package sul.protocol.minecraft107.clientbound;

import java.util.UUID;

import sul.protocol.minecraft107.types.*;
import sul.utils.*;

class UpdateHealth extends Packet {

	public final static int ID = (int)62;

	public final static boolean CLIENTBOUND = true;
	public final static boolean SERVERBOUND = false;

	public float health;
	public int hunger;
	public float saturation;

	@Override
	public int length() {
		return Var.Uint.length(hunger) + 8;
	}

	@Override
	public byte[] encode() {
	}

	@Override
	public void decode(byte[] buffer) {
	}

}
