/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 *
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/minecraft109.xml
 */
package sul.protocol.minecraft109.clientbound;

import sul.utils.*;

public class SetPassengers extends Packet {

	public final static int ID = (int)64;

	public final static boolean CLIENTBOUND = true;
	public final static boolean SERVERBOUND = false;

	public int entityId;
	public int[] passengers;

	public SetPassengers() {}

	public SetPassengers(int entityId, int[] passengers) {
		this.entityId = entityId;
		this.passengers = passengers;
	}

	@Override
	public int length() {
		int length=Var.Uint.length() + Var.Uint.length(entityId) + Var.Uint.length(passengers.length) + 0; for(int cgfzc2vuz2vycw:passengers){ length+=Var.Uint.length(cgfzc2vuz2vycw); } return length;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeVaruint(ID);
		this.writeVaruint(entityId);
		this.writeVaruint((int)passengers.length); for(int cgfzc2vuz2vycw:passengers){ this.writeVaruint(cgfzc2vuz2vycw); }
		return this._buffer;
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		varuint.decode(_buffer, _index);
		entityId=varuint.decode(_buffer, _index);
		int bhbhc3nlbmdlcnm=varuint.decode(_buffer, _index); passengers=new int[bhbhc3nlbmdlcnm]; for(int cgfzc2vuz2vycw=0;cgfzc2vuz2vycw<passengers.length;cgfzc2vuz2vycw++){ passengers[cgfzc2vuz2vycw]=varuint.decode(_buffer, _index); }
	}

	public static SetPassengers fromBuffer(byte[] buffer) {
		SetPassengers ret = new SetPassengers();
		ret.decode(buffer);
		return ret;
	}

}
