/*
 * This file has been automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 *
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generator: https://github.com/sel-project/sel-utils/blob/master/xml/protocol/raknet8.xml
 */
package sul.protocol.raknet8.control;

import java.util.UUID;

import sul.protocol.raknet8.types.*;
import sul.utils.*;

class Ack extends Packet {

	public final static byte ID = (byte)192;

	public final static boolean CLIENTBOUND = true;
	public final static boolean SERVERBOUND = true;

	public Acknowledge[] packets;

	@Override
	public int length() {
	}

	@Override
	public byte[] encode() {
		this.buffer = new byte[this.length()];
		this.index = 0;
		this.writeByteB(ID);
		this.writeShortB((short)packets.length); for(acknowledge cgfja2v0cw:packets){ this.writeBytes(cgfja2v0cw.encode()); }
		return this.buffer;
	}

	@Override
	public void decode(byte[] buffer) {
		this.buffer = buffer;
		this.index = 0;
	}

}
