/*
 * This file has been automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 *
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generator: https://github.com/sel-project/sel-utils/blob/master/xml/protocol/minecraft47.xml
 */
package sul.protocol.minecraft47.clientbound;

import java.util.UUID;

import sul.protocol.minecraft47.types.*;
import sul.utils.*;

class SpawnPainting extends Packet {

	public final static int ID = (int)16;

	public final static boolean CLIENTBOUND = true;
	public final static boolean SERVERBOUND = false;

	// direction
	public final static byte NORTH = (byte)0;
	public final static byte WEST = (byte)1;
	public final static byte SOUTH = (byte)2;
	public final static byte EAST = (byte)3;

	public int entityId;
	public String title;
	public long position;
	public byte direction;

	@Override
	public int length() {
		return Var.Uint.length(entityId) + Var.Uint.length(title.getBytes(StandardCharset.UTF_8).length) + title.getBytes(StandardCharset.UTF_8).length + 9;
	}

	@Override
	public byte[] encode() {
	}

	@Override
	public void decode(byte[] buffer) {
	}

}
