/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/hncom2.xml
 */
package sul.protocol.hncom2.world;

import sul.utils.*;

public class UpdateDifficulty extends Packet {

	public static final byte ID = (byte)33;

	public static final boolean CLIENTBOUND = false;
	public static final boolean SERVERBOUND = true;

	@Override
	public int getId() {
		return ID;
	}

	public int worldId;
	public byte difficulty;

	public UpdateDifficulty() {}

	public UpdateDifficulty(int worldId, byte difficulty) {
		this.worldId = worldId;
		this.difficulty = difficulty;
	}

	@Override
	public int length() {
		return Buffer.varuintLength(worldId) + 2;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeBigEndianByte(ID);
		this.writeVaruint(worldId);
		this.writeBigEndianByte(difficulty);
		return this.getBuffer();
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		readBigEndianByte();
		worldId=this.readVaruint();
		difficulty=readBigEndianByte();
	}

	public static UpdateDifficulty fromBuffer(byte[] buffer) {
		UpdateDifficulty ret = new UpdateDifficulty();
		ret.decode(buffer);
		return ret;
	}

	@Override
	public String toString() {
		return "UpdateDifficulty(worldId: " + this.worldId + ", difficulty: " + this.difficulty + ")";
	}

}
