const Creative = [

	{"name": "Coal", "id": 263, "meta": 0},
	{"name": "Charcoal", "id": 263, "meta": 1},
	{"name": "Diamond", "id": 264, "meta": 0},
	{"name": "Iron Ingot", "id": 265, "meta": 0},
	{"name": "Gold Ingot", "id": 266, "meta": 0},
	{"name": "Emerald", "id": 388, "meta": 0},
	{"name": "Stick", "id": 280, "meta": 0},
	{"name": "Bowl", "id": 281, "meta": 0},
	{"name": "String", "id": 287, "meta": 0},
	{"name": "Feather", "id": 288, "meta": 0},
	{"name": "Flint", "id": 318, "meta": 0},
	{"name": "Leather", "id": 334, "meta": 0},
	{"name": "Rabbit Hide", "id": 415, "meta": 0},
	{"name": "Clay", "id": 337, "meta": 0},
	{"name": "Sugar", "id": 353, "meta": 0},
	{"name": "Brick", "id": 336, "meta": 0},
	{"name": "Nether Brick", "id": 405, "meta": 0},
	{"name": "Nether Quartz", "id": 406, "meta": 0},
	{"name": "Paper", "id": 339, "meta": 0},
	{"name": "Book", "id": 340, "meta": 0},
	{"name": "Arrow", "id": 262, "meta": 0},
	{"name": "Bone", "id": 352, "meta": 0},
	{"name": "Empty Map", "id": 395, "meta": 0},
	{"name": "Sugar Canes", "id": 338, "meta": 0},
	{"name": "Wheat", "id": 296, "meta": 0},
	{"name": "Arrow of Night Vision", "id": 262, "meta": 5},
	{"name": "Arrow of Night Vision", "id": 262, "meta": 6},
	{"name": "Arrow of Invisibility", "id": 262, "meta": 7},
	{"name": "Arrow of Invisibility", "id": 262, "meta": 8},
	{"name": "Arrow of Leaping", "id": 262, "meta": 9},
	{"name": "Arrow of Leaping", "id": 262, "meta": 10},
	{"name": "Arrow of Leaping", "id": 262, "meta": 11},
	{"name": "Arrow of Fire Resistance", "id": 262, "meta": 12},
	{"name": "Arrow of Fire Resistance", "id": 262, "meta": 13},
	{"name": "Arrow of Swiftness", "id": 262, "meta": 14},
	{"name": "Arrow of Swiftness", "id": 262, "meta": 15},
	{"name": "Arrow of Swiftness", "id": 262, "meta": 16},
	{"name": "Arrow of Slowness", "id": 262, "meta": 17},
	{"name": "Arrow of Slowness", "id": 262, "meta": 18},
	{"name": "Arrow of Water Breathing", "id": 262, "meta": 19},
	{"name": "Arrow of Water Breathing", "id": 262, "meta": 20},
	{"name": "Arrow of Healing", "id": 262, "meta": 21},
	{"name": "Arrow of Healing", "id": 262, "meta": 22},
	{"name": "Arrow of Harming", "id": 262, "meta": 23},
	{"name": "Arrow of Harming", "id": 262, "meta": 24},
	{"name": "Arrow of Poison", "id": 262, "meta": 25},
	{"name": "Arrow of Poison", "id": 262, "meta": 26},
	{"name": "Arrow of Poison", "id": 262, "meta": 27},
	{"name": "Arrow of Regeneration", "id": 262, "meta": 28},
	{"name": "Arrow of Regeneration", "id": 262, "meta": 29},
	{"name": "Arrow of Regeneration", "id": 262, "meta": 30},
	{"name": "Arrow of Strength", "id": 262, "meta": 31},
	{"name": "Arrow of Strength", "id": 262, "meta": 32},
	{"name": "Arrow of Strength", "id": 262, "meta": 33},
	{"name": "Arrow of Weakness", "id": 262, "meta": 34},
	{"name": "Arrow of Weakness", "id": 262, "meta": 35},
	{"name": "Arrow of Decay", "id": 262, "meta": 36},
	{"name": "Seeds", "id": 295, "meta": 0},
	{"name": "Pumpkin Seeds", "id": 361, "meta": 0},
	{"name": "Melon Seeds", "id": 362, "meta": 0},
	{"name": "Beetroot Seeds", "id": 458, "meta": 0},
	{"name": "Egg", "id": 344, "meta": 0},
	{"name": "Apple", "id": 260, "meta": 0},
	{"name": "Golden Apple", "id": 322, "meta": 0},
	{"name": "Golden Apple", "id": 466, "meta": 0},
	{"name": "Raw Fish", "id": 349, "meta": 0},
	{"name": "Raw Salmon", "id": 460, "meta": 0},
	{"name": "Clownfish", "id": 461, "meta": 0},
	{"name": "Pufferfish", "id": 462, "meta": 0},
	{"name": "Cooked Fish", "id": 350, "meta": 0},
	{"name": "Cooked Salmon", "id": 463, "meta": 0},
	{"name": "Rotten flesh", "id": 367, "meta": 0},
	{"name": "Mushroom Stew", "id": 282, "meta": 0},
	{"name": "Bread", "id": 297, "meta": 0},
	{"name": "Raw Porkchop", "id": 319, "meta": 0},
	{"name": "Cooked Porkchop", "id": 320, "meta": 0},
	{"name": "Raw Chicken", "id": 365, "meta": 0},
	{"name": "Cooked Chicken", "id": 366, "meta": 0},
	{"name": "Raw Mutton", "id": 423, "meta": 0},
	{"name": "Cooked Mutton", "id": 424, "meta": 0},
	{"name": "Raw Beef", "id": 363, "meta": 0},
	{"name": "Steak", "id": 364, "meta": 0},
	{"name": "Melon", "id": 360, "meta": 0},
	{"name": "Carrot", "id": 391, "meta": 0},
	{"name": "Potato", "id": 392, "meta": 0},
	{"name": "Baked Potato", "id": 393, "meta": 0},
	{"name": "Poisonous Potato", "id": 394, "meta": 0},
	{"name": "Beetroot", "id": 457, "meta": 0},
	{"name": "Cookie", "id": 357, "meta": 0},
	{"name": "Pumpkin Pie", "id": 400, "meta": 0},
	{"name": "Raw Rabbit", "id": 411, "meta": 0},
	{"name": "Cooked Rabbit", "id": 412, "meta": 0},
	{"name": "Rabbit Stew", "id": 413, "meta": 0},
	{"name": "Chorus Fruit", "id": 432, "meta": 0},
	{"name": "Popped Chorus Fruit", "id": 433, "meta": 0},
	{"name": "Nether Star", "id": 399, "meta": 0},
	{"name": "Magma Cream", "id": 378, "meta": 0},
	{"name": "Blaze Rod", "id": 369, "meta": 0},
	{"name": "Gold Nugget", "id": 371, "meta": 0},
	{"name": "Golden Carrot", "id": 396, "meta": 0},
	{"name": "Glistering Melon", "id": 382, "meta": 0},
	{"name": "Rabbit's Foot", "id": 414, "meta": 0},
	{"name": "Ghast Tear", "id": 370, "meta": 0},
	{"name": "Slimeball", "id": 341, "meta": 0},
	{"name": "Blaze Powder", "id": 377, "meta": 0},
	{"name": "Nether Wart", "id": 372, "meta": 0},
	{"name": "Gunpowder", "id": 289, "meta": 0},
	{"name": "Glowstone Dust", "id": 348, "meta": 0},
	{"name": "Spider Eye", "id": 375, "meta": 0},
	{"name": "Fermented Spider Eye", "id": 376, "meta": 0},
	{"name": "Dragon's breath", "id": 437, "meta": 0},
	{"name": "Carrot on a stick", "id": 398, "meta": 0},
	{"name": "Bottle o' Enchanting", "id": 384, "meta": 0},
	{"name": "Shulker Shell", "id": 445, "meta": 0},
	{"name": "Prismarine Shard", "id": 409, "meta": 0},
	{"name": "Prismarine Crystals", "id": 422, "meta": 0},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 0, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 0, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 0, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 0, "level": 4}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 1, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 1, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 1, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 1, "level": 4}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 2, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 2, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 2, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 2, "level": 4}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 3, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 3, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 3, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 3, "level": 4}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 4, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 4, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 4, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 4, "level": 4}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 5, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 5, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 5, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 6, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 6, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 6, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 7, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 7, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 7, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 8, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 9, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 9, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 9, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 9, "level": 4}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 9, "level": 5}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 10, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 10, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 10, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 10, "level": 4}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 10, "level": 5}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 11, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 11, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 11, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 11, "level": 4}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 11, "level": 5}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 12, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 12, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 13, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 13, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 14, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 14, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 14, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 15, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 15, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 15, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 15, "level": 4}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 15, "level": 5}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 16, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 17, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 17, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 17, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 18, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 18, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 18, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 19, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 19, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 19, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 19, "level": 4}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 19, "level": 5}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 20, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 20, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 21, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 22, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 23, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 23, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 23, "level": 3}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 24, "level": 1}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 24, "level": 2}},
	{"name": "Enchanted Book", "id": 403, "meta": 0, "enchantment": {"type": 24, "level": 3}},
	{"name": "Ink Sac", "id": 351, "meta": 0},
	{"name": "Grey Dye", "id": 351, "meta": 8},
	{"name": "Light Grey Dye", "id": 351, "meta": 7},
	{"name": "Bone Meal", "id": 351, "meta": 15},
	{"name": "Light Blue Dye", "id": 351, "meta": 12},
	{"name": "Orange Dye", "id": 351, "meta": 14},
	{"name": "Rose Red", "id": 351, "meta": 1},
	{"name": "Lapis Lazuli", "id": 351, "meta": 4},
	{"name": "Purple Dye", "id": 351, "meta": 5},
	{"name": "Magenta Dye", "id": 351, "meta": 13},
	{"name": "Pink Dye", "id": 351, "meta": 9},
	{"name": "Cocoa Beans", "id": 351, "meta": 3},
	{"name": "Dandelion Yellow", "id": 351, "meta": 11},
	{"name": "Lime Dye", "id": 351, "meta": 10},
	{"name": "Cactus Green", "id": 351, "meta": 2},
	{"name": "Cyan Dye", "id": 351, "meta": 6},
	{"name": "Glass Bottle", "id": 374, "meta": 0},
	{"name": "Water Bottle", "id": 373, "meta": 0},
	{"name": "Mundane Potion", "id": 373, "meta": 1},
	{"name": "Mundane Potion", "id": 373, "meta": 2},
	{"name": "Thick Potion", "id": 373, "meta": 3},
	{"name": "Awkward Potion", "id": 373, "meta": 4},
	{"name": "Potion of Night Vision", "id": 373, "meta": 5},
	{"name": "Potion of Night Vision", "id": 373, "meta": 6},
	{"name": "Potion of Invisibility", "id": 373, "meta": 7},
	{"name": "Potion of Invisibility", "id": 373, "meta": 8},
	{"name": "Potion of Leaping", "id": 373, "meta": 9},
	{"name": "Potion of Leaping", "id": 373, "meta": 10},
	{"name": "Potion of Leaping", "id": 373, "meta": 11},
	{"name": "Potion of Fire Resistance", "id": 373, "meta": 12},
	{"name": "Potion of Fire Resistance", "id": 373, "meta": 13},
	{"name": "Potion of Swiftness", "id": 373, "meta": 14},
	{"name": "Potion of Swiftness", "id": 373, "meta": 15},
	{"name": "Potion of Swiftness", "id": 373, "meta": 16},
	{"name": "Potion of Slowness", "id": 373, "meta": 17},
	{"name": "Potion of Slowness", "id": 373, "meta": 18},
	{"name": "Potion of Water Breathing", "id": 373, "meta": 19},
	{"name": "Potion of Water Breathing", "id": 373, "meta": 20},
	{"name": "Potion of Healing", "id": 373, "meta": 21},
	{"name": "Potion of Healing", "id": 373, "meta": 22},
	{"name": "Potion of Harming", "id": 373, "meta": 23},
	{"name": "Potion of Harming", "id": 373, "meta": 24},
	{"name": "Potion of Poison", "id": 373, "meta": 25},
	{"name": "Potion of Poison", "id": 373, "meta": 26},
	{"name": "Potion of Poison", "id": 373, "meta": 27},
	{"name": "Potion of Regeneration", "id": 373, "meta": 28},
	{"name": "Potion of Regeneration", "id": 373, "meta": 29},
	{"name": "Potion of Regeneration", "id": 373, "meta": 30},
	{"name": "Potion of Strength", "id": 373, "meta": 31},
	{"name": "Potion of Strength", "id": 373, "meta": 32},
	{"name": "Potion of Strength", "id": 373, "meta": 33},
	{"name": "Potion of Weakness", "id": 373, "meta": 34},
	{"name": "Potion of Weakness", "id": 373, "meta": 35},
	{"name": "Potion of Decay", "id": 373, "meta": 36},
	{"name": "Splash Water Bottle", "id": 438, "meta": 0},
	{"name": "Splash Mundane Potion", "id": 438, "meta": 1},
	{"name": "Splash Mundane Potion", "id": 438, "meta": 2},
	{"name": "Splash Thick Potion", "id": 438, "meta": 3},
	{"name": "Splash Awkward Potion", "id": 438, "meta": 4},
	{"name": "Splash Potion of Night Vision", "id": 438, "meta": 5},
	{"name": "Splash Potion of Night Vision", "id": 438, "meta": 6},
	{"name": "Splash Potion of Invisibility", "id": 438, "meta": 7},
	{"name": "Splash Potion of Invisibility", "id": 438, "meta": 8},
	{"name": "Splash Potion of Leaping", "id": 438, "meta": 9},
	{"name": "Splash Potion of Leaping", "id": 438, "meta": 10},
	{"name": "Splash Potion of Leaping", "id": 438, "meta": 11},
	{"name": "Splash Potion of Fire Resistance", "id": 438, "meta": 12},
	{"name": "Splash Potion of Fire Resistance", "id": 438, "meta": 13},
	{"name": "Splash Potion of Swiftness", "id": 438, "meta": 14},
	{"name": "Splash Potion of Swiftness", "id": 438, "meta": 15},
	{"name": "Splash Potion of Swiftness", "id": 438, "meta": 16},
	{"name": "Splash Potion of Slowness", "id": 438, "meta": 17},
	{"name": "Splash Potion of Slowness", "id": 438, "meta": 18},
	{"name": "Splash Potion of Water Breathing", "id": 438, "meta": 19},
	{"name": "Splash Potion of Water Breathing", "id": 438, "meta": 20},
	{"name": "Splash Potion of Healing", "id": 438, "meta": 21},
	{"name": "Splash Potion of Healing", "id": 438, "meta": 22},
	{"name": "Splash Potion of Harming", "id": 438, "meta": 23},
	{"name": "Splash Potion of Harming", "id": 438, "meta": 24},
	{"name": "Splash Potion of Poison", "id": 438, "meta": 25},
	{"name": "Splash Potion of Poison", "id": 438, "meta": 26},
	{"name": "Splash Potion of Poison", "id": 438, "meta": 27},
	{"name": "Splash Potion of Regeneration", "id": 438, "meta": 28},
	{"name": "Splash Potion of Regeneration", "id": 438, "meta": 29},
	{"name": "Splash Potion of Regeneration", "id": 438, "meta": 30},
	{"name": "Splash Potion of Strength", "id": 438, "meta": 31},
	{"name": "Splash Potion of Strength", "id": 438, "meta": 32},
	{"name": "Splash Potion of Strength", "id": 438, "meta": 33},
	{"name": "Splash Potion of Weakness", "id": 438, "meta": 34},
	{"name": "Splash Potion of Weakness", "id": 438, "meta": 35},
	{"name": "Splash Potion of Decay", "id": 438, "meta": 36},
	{"name": "Lingering Water Bottle", "id": 466, "meta": 0},
	{"name": "Lingering Mundane Potion", "id": 466, "meta": 1},
	{"name": "Lingering Mundane Potion", "id": 466, "meta": 2},
	{"name": "Lingering Thick Potion", "id": 466, "meta": 3},
	{"name": "Lingering Awkward Potion", "id": 466, "meta": 4},
	{"name": "Lingering Potion of Night Vision", "id": 466, "meta": 5},
	{"name": "Lingering Potion of Night Vision", "id": 466, "meta": 6},
	{"name": "Lingering Potion of Invisibility", "id": 466, "meta": 7},
	{"name": "Lingering Potion of Invisibility", "id": 466, "meta": 8},
	{"name": "Lingering Potion of Leaping", "id": 466, "meta": 9},
	{"name": "Lingering Potion of Leaping", "id": 466, "meta": 10},
	{"name": "Lingering Potion of Leaping", "id": 466, "meta": 11},
	{"name": "Lingering Potion of Fire Resistance", "id": 466, "meta": 12},
	{"name": "Lingering Potion of Fire Resistance", "id": 466, "meta": 13},
	{"name": "Lingering Potion of Swiftness", "id": 466, "meta": 14},
	{"name": "Lingering Potion of Swiftness", "id": 466, "meta": 15},
	{"name": "Lingering Potion of Swiftness", "id": 466, "meta": 16},
	{"name": "Lingering Potion of Slowness", "id": 466, "meta": 17},
	{"name": "Lingering Potion of Slowness", "id": 466, "meta": 18},
	{"name": "Lingering Potion of Water Breathing", "id": 466, "meta": 19},
	{"name": "Lingering Potion of Water Breathing", "id": 466, "meta": 20},
	{"name": "Lingering Potion of Healing", "id": 466, "meta": 21},
	{"name": "Lingering Potion of Healing", "id": 466, "meta": 22},
	{"name": "Lingering Potion of Harming", "id": 466, "meta": 23},
	{"name": "Lingering Potion of Harming", "id": 466, "meta": 24},
	{"name": "Lingering Potion of Poison", "id": 466, "meta": 25},
	{"name": "Lingering Potion of Poison", "id": 466, "meta": 26},
	{"name": "Lingering Potion of Poison", "id": 466, "meta": 27},
	{"name": "Lingering Potion of Regeneration", "id": 466, "meta": 28},
	{"name": "Lingering Potion of Regeneration", "id": 466, "meta": 29},
	{"name": "Lingering Potion of Regeneration", "id": 466, "meta": 30},
	{"name": "Lingering Potion of Strength", "id": 466, "meta": 31},
	{"name": "Lingering Potion of Strength", "id": 466, "meta": 32},
	{"name": "Lingering Potion of Strength", "id": 466, "meta": 33},
	{"name": "Lingering Potion of Weakness", "id": 466, "meta": 34},
	{"name": "Lingering Potion of Weakness", "id": 466, "meta": 35},
	{"name": "Lingering Potion of Decay", "id": 466, "meta": 36},
	{"name": "Rail", "id": 66, "meta": 0},
	{"name": "Powered Rail", "id": 27, "meta": 0},
	{"name": "Detector Rail", "id": 28, "meta": 0},
	{"name": "Activator Rail", "id": 126, "meta": 0},
	{"name": "Torch", "id": 50, "meta": 0},
	{"name": "Bucket", "id": 325, "meta": 0},
	{"name": "Milk", "id": 325, "meta": 1},
	{"name": "Water Bucket", "id": 325, "meta": 8},
	{"name": "Lava Bucket", "id": 325, "meta": 10},
	{"name": "TNT", "id": 46, "meta": 0},
	{"name": "Lead", "id": 420, "meta": 0},
	{"name": "Name Tag", "id": 421, "meta": 0},
	{"name": "Redstone", "id": 331, "meta": 0},
	{"name": "Bow", "id": 261, "meta": 0},
	{"name": "Fishing Rod", "id": 346, "meta": 0},
	{"name": "Flint and Steel", "id": 259, "meta": 0},
	{"name": "Shears", "id": 359, "meta": 0},
	{"name": "Clock", "id": 347, "meta": 0},
	{"name": "Compass", "id": 345, "meta": 0},
	{"name": "Minecart", "id": 328, "meta": 0},
	{"name": "Minecart with Chest", "id": 342, "meta": 0},
	{"name": "Minecart with Hopper", "id": 408, "meta": 0},
	{"name": "Minecart with TNT", "id": 407, "meta": 0},
	{"name": "Oak Boat", "id": 333, "meta": 0},
	{"name": "Spruce Boat", "id": 333, "meta": 1},
	{"name": "Birch Boat", "id": 333, "meta": 2},
	{"name": "Jungle Boat", "id": 333, "meta": 3},
	{"name": "Acacia Boat", "id": 333, "meta": 4},
	{"name": "Dark Oak Boat", "id": 333, "meta": 5},
	{"name": "Saddle", "id": 329, "meta": 0},
	{"name": "Leather Horse Armor", "id": 416, "meta": 0},
	{"name": "Iron Horse Armor", "id": 417, "meta": 0},
	{"name": "Gold Horse Armor", "id": 418, "meta": 0},
	{"name": "Diamond Horse Armor", "id": 419, "meta": 0},
	{"name": "Spawn Villager", "id": 383, "meta": 15},
	{"name": "Spawn Chicken", "id": 383, "meta": 10},
	{"name": "Spawn Cow", "id": 383, "meta": 11},
	{"name": "Spawn Pig", "id": 383, "meta": 12},
	{"name": "Spawn Sheep", "id": 383, "meta": 13},
	{"name": "Spawn Wolf", "id": 383, "meta": 14},
	{"name": "Spawn Polar Bear", "id": 383, "meta": 28},
	{"name": "Spawn Ocelot", "id": 383, "meta": 22},
	{"name": "Spawn Mooshroom", "id": 383, "meta": 16},
	{"name": "Spawn Bat", "id": 383, "meta": 19},
	{"name": "Spawn Rabbit", "id": 383, "meta": 18},
	{"name": "Spawn Horse", "id": 383, "meta": 23},
	{"name": "Spawn Donkey", "id": 383, "meta": 24},
	{"name": "Spawn Mule", "id": 383, "meta": 25},
	{"name": "Spawn Skeleton Horse", "id": 383, "meta": 26},
	{"name": "Spawn Zombie Horse", "id": 383, "meta": 27},
	{"name": "Spawn Creeper", "id": 383, "meta": 33},
	{"name": "Spawn Enderman", "id": 383, "meta": 38},
	{"name": "Spawn Silverfish", "id": 383, "meta": 39},
	{"name": "Spawn Skeleton", "id": 383, "meta": 34},
	{"name": "Spawn Wither Horse", "id": 383, "meta": 48},
	{"name": "Spawn Stray", "id": 383, "meta": 46},
	{"name": "Spawn Slime", "id": 383, "meta": 37},
	{"name": "Spawn Spider", "id": 383, "meta": 35},
	{"name": "Spawn Zombie", "id": 383, "meta": 32},
	{"name": "Spawn Zombie Pigman", "id": 383, "meta": 36},
	{"name": "Spawn Husk", "id": 383, "meta": 47},
	{"name": "Spawn Squid", "id": 383, "meta": 17},
	{"name": "Spawn Cave Spider", "id": 383, "meta": 40},
	{"name": "Spawn Witch", "id": 383, "meta": 45},
	{"name": "Spawn Guardian", "id": 383, "meta": 49},
	{"name": "Spawn Elder Guardian", "id": 383, "meta": 50},
	{"name": "Spawn Endermite", "id": 383, "meta": 55},
	{"name": "Spawn Magma Cube", "id": 383, "meta": 42},
	{"name": "Spawn Ghast", "id": 383, "meta": 41},
	{"name": "Spawn Blaze", "id": 383, "meta": 43},
	{"name": "Spawn Shulker", "id": 383, "meta": 54},
	{"name": "Fire Charge", "id": 385, "meta": 0},
	{"name": "Wooden Sword", "id": 268, "meta": 0},
	{"name": "Wooden Hoe", "id": 290, "meta": 0},
	{"name": "Wooden Shovel", "id": 269, "meta": 0},
	{"name": "Wooden Pickaxe", "id": 270, "meta": 0},
	{"name": "Wooden Axe", "id": 271, "meta": 0},
	{"name": "Stone Sword", "id": 272, "meta": 0},
	{"name": "Stone Hoe", "id": 291, "meta": 0},
	{"name": "Stone Shovel", "id": 273, "meta": 0},
	{"name": "Stone Pickaxe", "id": 274, "meta": 0},
	{"name": "Stone Axe", "id": 275, "meta": 0},
	{"name": "Iron Sword", "id": 267, "meta": 0},
	{"name": "Iron Hoe", "id": 292, "meta": 0},
	{"name": "Iron Shovel", "id": 256, "meta": 0},
	{"name": "Iron Pickaxe", "id": 257, "meta": 0},
	{"name": "Iron Axe", "id": 258, "meta": 0},
	{"name": "Diamond Sword", "id": 276, "meta": 0},
	{"name": "Diamond Hoe", "id": 293, "meta": 0},
	{"name": "Diamond Shovel", "id": 277, "meta": 0},
	{"name": "Diamond Pickaxe", "id": 278, "meta": 0},
	{"name": "Diamond Axe", "id": 279, "meta": 0},
	{"name": "Golden Sword", "id": 283, "meta": 0},
	{"name": "Golden Hoe", "id": 294, "meta": 0},
	{"name": "Golden Shovel", "id": 284, "meta": 0},
	{"name": "Golden Pickaxe", "id": 285, "meta": 0},
	{"name": "Golden Axe", "id": 286, "meta": 0},
	{"name": "Leather Cap", "id": 298, "meta": 0},
	{"name": "Leather Tunic", "id": 299, "meta": 0},
	{"name": "Leather Pants", "id": 300, "meta": 0},
	{"name": "Leather Boots", "id": 301, "meta": 0},
	{"name": "Chain Helmet", "id": 302, "meta": 0},
	{"name": "Chain Chestplate", "id": 303, "meta": 0},
	{"name": "Chain Leggings", "id": 304, "meta": 0},
	{"name": "Chain Boots", "id": 305, "meta": 0},
	{"name": "Iron Helmet", "id": 306, "meta": 0},
	{"name": "Iron Chestplate", "id": 307, "meta": 0},
	{"name": "Iron Leggings", "id": 308, "meta": 0},
	{"name": "Iron Boots", "id": 309, "meta": 0},
	{"name": "Diamond Helmet", "id": 310, "meta": 0},
	{"name": "Diamond Chestplate", "id": 311, "meta": 0},
	{"name": "Diamond Leggings", "id": 312, "meta": 0},
	{"name": "Diamond Boots", "id": 313, "meta": 0},
	{"name": "Golden Helmet", "id": 314, "meta": 0},
	{"name": "Golden Chestplate", "id": 315, "meta": 0},
	{"name": "Golden Leggings", "id": 316, "meta": 0},
	{"name": "Golden Boots", "id": 317, "meta": 0},
	{"name": "Elytra Wings", "id": 444, "meta": 0},
	{"name": "Lever", "id": 69, "meta": 0},
	{"name": "Redstone Lamp", "id": 123, "meta": 0},
	{"name": "Redstone Torch", "id": 76, "meta": 0},
	{"name": "Wooden Pressure Plate", "id": 72, "meta": 0},
	{"name": "Stone Pressure Plate", "id": 70, "meta": 0},
	{"name": "Weighted Pressure Plate (Light)", "id": 147, "meta": 0},
	{"name": "Weighted Pressure Plate (Heavy)", "id": 148, "meta": 0},
	{"name": "Button", "id": 143, "meta": 5},
	{"name": "Button", "id": 77, "meta": 5},
	{"name": "Daylight Sensor", "id": 151, "meta": 0},
	{"name": "Tripwire Hook", "id": 131, "meta": 0},
	{"name": "Redstone Repeater", "id": 356, "meta": 0},
	{"name": "Redstone Comparator", "id": 404, "meta": 0},
	{"name": "Dispenser", "id": 23, "meta": 3},
	{"name": "Dropper", "id": 125, "meta": 3},
	{"name": "Piston", "id": 33, "meta": 1},
	{"name": "Sticky Piston", "id": 29, "meta": 1},
	{"name": "Observer", "id": 251, "meta": 0},
	{"name": "Hopper", "id": 410, "meta": 0},
	{"name": "Snowball", "id": 332, "meta": 0},
	{"name": "Ender Pearl", "id": 368, "meta": 0},
	{"name": "Eye of Ender", "id": 381, "meta": 0},
	{"name": "Beacon", "id": 138, "meta": 0},
	{"name": "Cobblestone Wall", "id": 139, "meta": 0},
	{"name": "Mossy Cobblestone Wall", "id": 139, "meta": 1},
	{"name": "Lily Pad", "id": 111, "meta": 0},
	{"name": "Sea Lantern", "id": 169, "meta": 0},
	{"name": "Chorus Plant", "id": 240, "meta": 0},
	{"name": "Chorus Flower", "id": 200, "meta": 0},
	{"name": "Block of Gold", "id": 41, "meta": 0},
	{"name": "Block of Iron", "id": 42, "meta": 0},
	{"name": "Block of Diamond", "id": 57, "meta": 0},
	{"name": "Lapis Lazuli Block", "id": 22, "meta": 0},
	{"name": "Block of Coal", "id": 173, "meta": 0},
	{"name": "Block of Emerald", "id": 133, "meta": 0},
	{"name": "Block of Redstone", "id": 152, "meta": 0},
	{"name": "Top Snow", "id": 78, "meta": 0},
	{"name": "Glass", "id": 20, "meta": 0},
	{"name": "Glowstone", "id": 89, "meta": 0},
	{"name": "Vines", "id": 106, "meta": 0},
	{"name": "Ladder", "id": 65, "meta": 0},
	{"name": "Sponge", "id": 19, "meta": 0},
	{"name": "Wet Sponge", "id": 19, "meta": 1},
	{"name": "Glass Pane", "id": 102, "meta": 0},
	{"name": "Oak Door", "id": 324, "meta": 0},
	{"name": "Spruce Door", "id": 427, "meta": 0},
	{"name": "Birch Door", "id": 428, "meta": 0},
	{"name": "Jungle Door", "id": 429, "meta": 0},
	{"name": "Acacia Door", "id": 430, "meta": 0},
	{"name": "Dark Oak Wood", "id": 431, "meta": 0},
	{"name": "Iron Door", "id": 330, "meta": 0},
	{"name": "Wooden Trapdoor", "id": 96, "meta": 0},
	{"name": "Iron Trapdoor", "id": 167, "meta": 0},
	{"name": "Oak Fence", "id": 85, "meta": 0},
	{"name": "Spruce Fence gate", "id": 85, "meta": 1},
	{"name": "Birch Fence", "id": 85, "meta": 2},
	{"name": "Jungle Fence", "id": 85, "meta": 3},
	{"name": "Acacia Fence", "id": 85, "meta": 4},
	{"name": "Dark Oak Fence", "id": 85, "meta": 5},
	{"name": "Nether Brick Fence", "id": 113, "meta": 0},
	{"name": "Oak Fence Gate", "id": 107, "meta": 0},
	{"name": "Spruce Fence Gate", "id": 183, "meta": 0},
	{"name": "Birch Fence Gate", "id": 184, "meta": 0},
	{"name": "Jungle Fence Gate", "id": 185, "meta": 0},
	{"name": "Acacia Fence Gate", "id": 187, "meta": 0},
	{"name": "Dark Oak Fence Gate", "id": 186, "meta": 0},
	{"name": "Iron Bars", "id": 101, "meta": 0},
	{"name": "Bed", "id": 355, "meta": 0},
	{"name": "Bookshelf", "id": 47, "meta": 0},
	{"name": "Sign", "id": 323, "meta": 0},
	{"name": "Painting", "id": 321, "meta": 0},
	{"name": "Item Frame", "id": 389, "meta": 0},
	{"name": "Crafting Table", "id": 58, "meta": 0},
	{"name": "Stonecutter", "id": 245, "meta": 0},
	{"name": "Chest", "id": 54, "meta": 0},
	{"name": "Trapped Chest", "id": 146, "meta": 0},
	{"name": "Furnace", "id": 61, "meta": 0},
	{"name": "Brewing Stand", "id": 379, "meta": 0},
	{"name": "Cauldron", "id": 380, "meta": 0},
	{"name": "Note Block", "id": 25, "meta": 0},
	{"name": "End Rod", "id": 208, "meta": 0},
	{"name": "End Portal", "id": 120, "meta": 0},
	{"name": "Anvil", "id": 145, "meta": 0},
	{"name": "Slightly Damaged Anvil", "id": 145, "meta": 4},
	{"name": "Very Damaged Anvil", "id": 145, "meta": 8},
	{"name": "Dandelion", "id": 37, "meta": 0},
	{"name": "Poppy", "id": 38, "meta": 0},
	{"name": "Blue Orchid", "id": 38, "meta": 1},
	{"name": "Allium", "id": 38, "meta": 2},
	{"name": "Azure Bluet", "id": 38, "meta": 3},
	{"name": "Red Tulip", "id": 38, "meta": 4},
	{"name": "Orange Tulip", "id": 38, "meta": 5},
	{"name": "White Tulip", "id": 38, "meta": 6},
	{"name": "Pink Tulip", "id": 38, "meta": 7},
	{"name": "Oxeye Daisy", "id": 38, "meta": 8},
	{"name": "Sunflower", "id": 175, "meta": 0},
	{"name": "Lilac", "id": 175, "meta": 1},
	{"name": "Double Tallgrass", "id": 175, "meta": 2},
	{"name": "Large Fern", "id": 175, "meta": 3},
	{"name": "Rose Bush", "id": 175, "meta": 4},
	{"name": "Peony", "id": 175, "meta": 5},
	{"name": "Mushroom", "id": 39, "meta": 0},
	{"name": "Mushroom", "id": 40, "meta": 0},
	{"name": "Mushroom", "id": 99, "meta": 14},
	{"name": "Mushroom", "id": 100, "meta": 14},
	{"name": "Mushroom", "id": 99, "meta": 0},
	{"name": "Mushroom", "id": 99, "meta": 15},
	{"name": "Cactus", "id": 81, "meta": 0},
	{"name": "Melon", "id": 103, "meta": 0},
	{"name": "Pumpkin", "id": 86, "meta": 0},
	{"name": "Jack o'Lantern", "id": 91, "meta": 0},
	{"name": "Cobweb", "id": 30, "meta": 0},
	{"name": "Hay Bale", "id": 170, "meta": 0},
	{"name": "Grass", "id": 31, "meta": 1},
	{"name": "Fern", "id": 31, "meta": 2},
	{"name": "Dead Bush", "id": 32, "meta": 0},
	{"name": "Oak Sapling", "id": 6, "meta": 0},
	{"name": "Spruce Sapling", "id": 6, "meta": 1},
	{"name": "Birch Sapling", "id": 6, "meta": 2},
	{"name": "Jungle Sapling", "id": 6, "meta": 3},
	{"name": "Acacia Sapling", "id": 6, "meta": 4},
	{"name": "Dark Oak Sapling", "id": 6, "meta": 5},
	{"name": "Oak Leaves", "id": 18, "meta": 0},
	{"name": "Spruce Leaves", "id": 18, "meta": 1},
	{"name": "Birch Leaves", "id": 18, "meta": 2},
	{"name": "Jungle Leaves", "id": 18, "meta": 3},
	{"name": "Acacia Leaves", "id": 161, "meta": 0},
	{"name": "Dark Oak Leaves", "id": 161, "meta": 1},
	{"name": "Cake", "id": 354, "meta": 0},
	{"name": "Skeleton Skull", "id": 397, "meta": 0},
	{"name": "Wither Skeleton Skull", "id": 397, "meta": 1},
	{"name": "Zombie Head", "id": 397, "meta": 2},
	{"name": "Head", "id": 397, "meta": 3},
	{"name": "Creeper Head", "id": 397, "meta": 4},
	{"name": "Dragon Head", "id": 397, "meta": 5},
	{"name": "Flower Pot", "id": 390, "meta": 0},
	{"name": "Stone Monster Egg", "id": 92, "meta": 0},
	{"name": "Cobblestone Monster Egg", "id": 92, "meta": 1},
	{"name": "Stone Brick Monster Egg", "id": 92, "meta": 2},
	{"name": "Mossy Stone Brick Monster Egg", "id": 92, "meta": 3},
	{"name": "Cracked Stone Brick Monster Egg", "id": 92, "meta": 4},
	{"name": "Chiseled Stone Brick Monster Egg", "id": 92, "meta": 5},
	{"name": "Dragon Egg", "id": 122, "meta": 0},
	{"name": "End Crystal", "id": 71, "meta": 0},
	{"name": "Monster Spawner", "id": 52, "meta": 0},
	{"name": "Enchantment Table", "id": 116, "meta": 0},
	{"name": "Slime Block", "id": 165, "meta": 0},
	{"name": "Ender Chest", "id": 130, "meta": 0},
	{"name": "Wool", "id": 35, "meta": 0},
	{"name": "Light Grey Wool", "id": 35, "meta": 8},
	{"name": "Grey Wool", "id": 35, "meta": 7},
	{"name": "Black Wool", "id": 35, "meta": 15},
	{"name": "Brown Wool", "id": 35, "meta": 12},
	{"name": "Red Wool", "id": 35, "meta": 14},
	{"name": "Orange Wool", "id": 35, "meta": 1},
	{"name": "Yellow Wool", "id": 35, "meta": 4},
	{"name": "Lime Wool", "id": 35, "meta": 5},
	{"name": "Green Wool", "id": 35, "meta": 13},
	{"name": "Cyan Wool", "id": 35, "meta": 9},
	{"name": "Light Blue Wool", "id": 35, "meta": 3},
	{"name": "Blue Wool", "id": 35, "meta": 11},
	{"name": "Purple Wool", "id": 35, "meta": 10},
	{"name": "Magenta Wool", "id": 35, "meta": 2},
	{"name": "Pink Wool", "id": 35, "meta": 6},
	{"name": "Carpet", "id": 171, "meta": 0},
	{"name": "Light Grey Carpet", "id": 171, "meta": 8},
	{"name": "Grey Carpet", "id": 171, "meta": 7},
	{"name": "Black Carpet", "id": 171, "meta": 15},
	{"name": "Brown Carpet", "id": 171, "meta": 12},
	{"name": "Red Carpet", "id": 171, "meta": 14},
	{"name": "Orange Carpet", "id": 171, "meta": 1},
	{"name": "Yellow Carpet", "id": 171, "meta": 4},
	{"name": "Lime Carpet", "id": 171, "meta": 5},
	{"name": "Green Carpet", "id": 171, "meta": 13},
	{"name": "Cyan Carpet", "id": 171, "meta": 9},
	{"name": "Light Blue Carpet", "id": 171, "meta": 3},
	{"name": "Blue Carpet", "id": 171, "meta": 11},
	{"name": "Purple Carpet", "id": 171, "meta": 10},
	{"name": "Magenta Carpet", "id": 171, "meta": 2},
	{"name": "Pink Carpet", "id": 171, "meta": 6},
	{"name": "Cobblestone", "id": 4, "meta": 0},
	{"name": "Stone Bricks", "id": 98, "meta": 0},
	{"name": "Mossy Stone Bricks", "id": 98, "meta": 1},
	{"name": "Cracked Stone Bricks", "id": 98, "meta": 2},
	{"name": "Chiseled Stone Bricks", "id": 98, "meta": 3},
	{"name": "Moss Stone", "id": 48, "meta": 0},
	{"name": "Oak Wood Planks", "id": 5, "meta": 0},
	{"name": "Spruce Wood Planks", "id": 5, "meta": 1},
	{"name": "Birch Wood Planks", "id": 5, "meta": 2},
	{"name": "Jungle Wood Planks", "id": 5, "meta": 3},
	{"name": "Acacia Wood Planks", "id": 5, "meta": 4},
	{"name": "Dark Oak Wood Planks", "id": 5, "meta": 5},
	{"name": "Bricks", "id": 45, "meta": 0},
	{"name": "Stone", "id": 1, "meta": 0},
	{"name": "Granite", "id": 1, "meta": 1},
	{"name": "Polished Granite", "id": 1, "meta": 2},
	{"name": "Diorite", "id": 1, "meta": 3},
	{"name": "Polished Diorite", "id": 1, "meta": 4},
	{"name": "Andesite", "id": 1, "meta": 5},
	{"name": "Polished Andesite", "id": 1, "meta": 6},
	{"name": "Dirt", "id": 3, "meta": 0},
	{"name": "Podzol", "id": 243, "meta": 0},
	{"name": "Grass Block", "id": 2, "meta": 0},
	{"name": "Mycelium", "id": 110, "meta": 0},
	{"name": "Clay", "id": 82, "meta": 0},
	{"name": "Hardened Clay", "id": 172, "meta": 0},
	{"name": "White Stained Clay", "id": 159, "meta": 0},
	{"name": "Orange Stained Clay", "id": 159, "meta": 1},
	{"name": "Magenta Stained Clay", "id": 159, "meta": 2},
	{"name": "Light Blue Stained Clay", "id": 159, "meta": 3},
	{"name": "Yellow Stained Clay", "id": 159, "meta": 4},
	{"name": "Lime Stained Clay", "id": 159, "meta": 5},
	{"name": "Pink Stained Clay", "id": 159, "meta": 6},
	{"name": "Grey Stained Clay", "id": 159, "meta": 7},
	{"name": "Light Grey Stained Clay", "id": 159, "meta": 8},
	{"name": "Cyan Stained Clay", "id": 159, "meta": 9},
	{"name": "Purple Stained Clay", "id": 159, "meta": 10},
	{"name": "Blue Stained Clay", "id": 159, "meta": 11},
	{"name": "Brown Stained Clay", "id": 159, "meta": 12},
	{"name": "Green Stained Clay", "id": 159, "meta": 13},
	{"name": "Red Stained Clay", "id": 159, "meta": 14},
	{"name": "Black Stained Clay", "id": 159, "meta": 15},
	{"name": "Sandstone", "id": 24, "meta": 0},
	{"name": "Chiseled Sandstone", "id": 24, "meta": 1},
	{"name": "Smooth Sandstone", "id": 24, "meta": 2},
	{"name": "Red Sandstone", "id": 179, "meta": 0},
	{"name": "Chiseled Red Sandstone", "id": 179, "meta": 1},
	{"name": "Smooth Red Sandstone", "id": 179, "meta": 2},
	{"name": "Sand", "id": 12, "meta": 0},
	{"name": "Red Sand", "id": 12, "meta": 1},
	{"name": "Gravel", "id": 13, "meta": 0},
	{"name": "Oak Wood", "id": 17, "meta": 0},
	{"name": "Spruce Wood", "id": 17, "meta": 1},
	{"name": "Birch Wood", "id": 17, "meta": 2},
	{"name": "Jungle Wood", "id": 17, "meta": 3},
	{"name": "Acacia Wood", "id": 162, "meta": 0},
	{"name": "Dark Oak Wood", "id": 162, "meta": 1},
	{"name": "Nether Brick", "id": 112, "meta": 0},
	{"name": "Netherrack", "id": 87, "meta": 0},
	{"name": "Soul Sand", "id": 88, "meta": 0},
	{"name": "Bedrock", "id": 7, "meta": 0},
	{"name": "Cobblestone Stairs", "id": 67, "meta": 0},
	{"name": "Oak Wood Stairs", "id": 53, "meta": 0},
	{"name": "Spruce Wood Stairs", "id": 134, "meta": 0},
	{"name": "Birch Wood Stairs", "id": 135, "meta": 0},
	{"name": "Jungle Wood Stairs", "id": 136, "meta": 0},
	{"name": "Acacia Wood Stairs", "id": 163, "meta": 0},
	{"name": "Dark Oak Wood Stairs", "id": 164, "meta": 0},
	{"name": "Brick Stairs", "id": 108, "meta": 0},
	{"name": "Sandstone Stairs", "id": 128, "meta": 0},
	{"name": "Red Sandstone Stairs", "id": 180, "meta": 0},
	{"name": "Stone Brick Stairs", "id": 109, "meta": 0},
	{"name": "Nether brick Stairs", "id": 114, "meta": 0},
	{"name": "Quartz Stairs", "id": 156, "meta": 0},
	{"name": "Purpur Stairs", "id": 203, "meta": 0},
	{"name": "Stone Slab", "id": 44, "meta": 0},
	{"name": "Cobblestone Slab", "id": 44, "meta": 3},
	{"name": "Oak Wood Slab", "id": 158, "meta": 0},
	{"name": "Spruce Wood Slab", "id": 158, "meta": 1},
	{"name": "Birch Wood Slab", "id": 158, "meta": 2},
	{"name": "Jungle Wood Slab", "id": 158, "meta": 3},
	{"name": "Acacia Wood Slab", "id": 158, "meta": 4},
	{"name": "Dark Oak Wood Slab", "id": 158, "meta": 5},
	{"name": "Bricks Slab", "id": 44, "meta": 4},
	{"name": "Sandstone Slab", "id": 44, "meta": 1},
	{"name": "Red Sandstone Slab", "id": 182, "meta": 0},
	{"name": "Stone Bricks Slab", "id": 44, "meta": 5},
	{"name": "Nether Brick Slab", "id": 44, "meta": 7},
	{"name": "Quartz Slab", "id": 44, "meta": 6},
	{"name": "Purpur Slab", "id": 205, "meta": 0},
	{"name": "Block of Quartz", "id": 155, "meta": 0},
	{"name": "Pillar Quartz Block", "id": 155, "meta": 1},
	{"name": "Chiseled Quartz Block", "id": 155, "meta": 2},
	{"name": "Prismarine", "id": 168, "meta": 0},
	{"name": "Prismarine Bricks", "id": 168, "meta": 1},
	{"name": "Dark Prismarine", "id": 168, "meta": 2},
	{"name": "Purpur Block", "id": 201, "meta": 0},
	{"name": "Purpur Pillar", "id": 201, "meta": 2},
	{"name": "Coal Ore", "id": 16, "meta": 0},
	{"name": "Iron Ore", "id": 15, "meta": 0},
	{"name": "Gold Ore", "id": 14, "meta": 0},
	{"name": "Diamond Ore", "id": 56, "meta": 0},
	{"name": "Lapis Lazuli Ore", "id": 21, "meta": 0},
	{"name": "Redstone Ore", "id": 73, "meta": 0},
	{"name": "Emerald Ore", "id": 129, "meta": 0},
	{"name": "Nether Quartz Ore", "id": 153, "meta": 0},
	{"name": "Obsidian", "id": 49, "meta": 0},
	{"name": "Ice", "id": 79, "meta": 0},
	{"name": "Packed Ice", "id": 174, "meta": 0},
	{"name": "Snow", "id": 80, "meta": 0},
	{"name": "End Stone Brick", "id": 206, "meta": 0},
	{"name": "End Stone", "id": 121, "meta": 0},

]
