/*
 * This file has been automatically generated by sel-utils and
 * it's released under the GNU General Public License version 3.
 *
 * Repository: https://github.com/sel-project/sel-utils
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * From: https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket100.xml
 */
package sul.protocol.pocket100.play;

import java.util.UUID;

import sul.protocol.pocket100.types.*;
import sul.utils.Packet;

class StartGame extends Packet {

	public final static byte ID = (byte)12;

	public final static boolean CLIENTBOUND = true;
	public final static boolean SERVERBOUND = false;

	// dimension
	public final static int OVERWORLD = (int)0;
	public final static int NETHER = (int)1;
	public final static int END = (int)2;

	// generator
	public final static int OLD = (int)0;
	public final static int INFINITE = (int)1;
	public final static int FLAT = (int)2;

	// world gamemode
	public final static int SURVIVAL = (int)0;
	public final static int CREATIVE = (int)1;

	// difficulty
	public final static int PEACEFUL = (int)0;
	public final static int EASY = (int)1;
	public final static int NORMAL = (int)2;
	public final static int HARD = (int)3;

	// edition
	public final static byte CLASSIC = (byte)0;
	public final static byte EDUCATION = (byte)1;

	public long entityId;
	public long runtimeId;
	public float<xyz> position;
	public float yaw;
	public float pitch;
	public int seed;
	public int dimension;
	public int generator;
	public int worldGamemode;
	public int difficulty;
	public int<xyz> spawnPosition;
	public boolean loadedInCreative;
	public int time;
	public byte edition;
	public float rainLevel;
	public float lightingLevel;
	public boolean cheatsEnabled;
	public boolean textureRequired;
	public String levelId;
	public String worldName;

	@Override
	public byte[] encode() {
	}

	@Override
	public void decode(byte[] buffer) {
	}

}
