/*
 * This file has been automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 *
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generator: https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket100.xml
 */
package sul.protocol.pocket100.play;

import java.util.UUID;

import sul.protocol.pocket100.types.*;
import sul.utils.*;

class UpdateBlock extends Packet {

	public final static byte ID = (byte)23;

	public final static boolean CLIENTBOUND = true;
	public final static boolean SERVERBOUND = false;

	// flags and meta
	public static immutable int NEIGHBORS = 1;
	public static immutable int NETWORK = 2;
	public static immutable int NO_GRAPHIC = 4;
	public static immutable int PRIORITY = 8;

	public BlockPosition position;
	public int block;
	public int flagsAndMeta;

	@Override
	public int length() {
	}

	@Override
	public byte[] encode() {
		this.buffer = new byte[this.length()];
		this.index = 0;
		this.writeByteB(ID);
		this.writeBytes(position.encode());
		this.writeVaruint(block);
		this.writeVaruint(flagsAndMeta);
		return this.buffer;
	}

	@Override
	public void decode(byte[] buffer) {
		this.buffer = buffer;
		this.index = 0;
	}

}
