/*
 * This file has been automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 *
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generator: https://github.com/sel-project/sel-utils/blob/master/xml/protocol/hncom1.xml
 */
package sul.protocol.hncom1.login;

import java.util.UUID;

import sul.protocol.hncom1.types.*;
import sul.utils.*;

class Info extends Packet {

	public final static byte ID = (byte)2;

	public final static boolean CLIENTBOUND = true;
	public final static boolean SERVERBOUND = false;

	public long serverId;
	public boolean onlineMode;
	public String displayName;
	public Game[] games;
	public int online;
	public int max;
	public String language;
	public String[] acceptedLanguages;
	public String[] nodes;
	public String socialJson;
	public String additionalJson;

	@Override
	public int length() {
		return Var.Uint.length(displayName.getBytes(StandardCharset.UTF_8).length) + displayName.getBytes(StandardCharset.UTF_8).length + Var.Uint.length(games.length) + games.length() + Var.Uint.length(online) + Var.Uint.length(max) + Var.Uint.length(language.getBytes(StandardCharset.UTF_8).length) + language.getBytes(StandardCharset.UTF_8).length + Var.Uint.length(acceptedLanguages.length) + acceptedLanguages.length() + Var.Uint.length(nodes.length) + nodes.length() + Var.Uint.length(socialJson.getBytes(StandardCharset.UTF_8).length) + socialJson.getBytes(StandardCharset.UTF_8).length + Var.Uint.length(additionalJson.getBytes(StandardCharset.UTF_8).length) + additionalJson.getBytes(StandardCharset.UTF_8).length + 9;
	}

	@Override
	public byte[] encode() {
	}

	@Override
	public void decode(byte[] buffer) {
	}

}
